spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zacboot?useUnicode=true&character_set_server=utf8mb4&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL&allowPublicKeyRetrieval=true
    username: root
    password: mysql417298...
    hikari:
      #最小空闲链接数量
      minimum-idle: 5
      #空闲连接存活最大时间（默认600000）
      idle-timeout: 180000
      #最大连接数
      maximum-pool-size: 10
      #是否自动提交
      auto-commit: true
      #连接池中链接的最长生命周期默认30分钟 = 1800000
      max-lifetime: 1800000
      #链接超时时间
      connection-timeout: 30000
      connection-test-query: SELECT 1
    redis:
      database: 0
      port: 6379
      host: localhost
      password:
      key:
        admin: 'ums:admin'
        resourceList: 'ums:resourceList'
      expire:
        common: 86400 # 24小时
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
      config:
        server-addr: http://localhost:8848
        file-extension: yaml
logging:
  level:
    root: debug
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: zacboot-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头