package com.zacboot.autocode.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.zacboot.autocode.dto.SysDept;
import com.zacboot.autocode.dto.example.SysDeptExample;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface SysDeptMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..sys_dept
     *
     * @mbg.generated Sat Dec 10 19:13:25 CST 2022
     */
    @SelectProvider(type=SysDeptSqlProvider.class, method="countByExample")
    long countByExample(SysDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..sys_dept
     *
     * @mbg.generated Sat Dec 10 19:13:25 CST 2022
     */
    @DeleteProvider(type=SysDeptSqlProvider.class, method="deleteByExample")
    int deleteByExample(SysDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..sys_dept
     *
     * @mbg.generated Sat Dec 10 19:13:25 CST 2022
     */
    @Insert({
        "insert into sys_dept (parent_uuid, depart_name, ",
        "description, mobile, ",
        "leader_uuid, dept_address, ",
        "uuid, create_user, ",
        "create_time, update_user, ",
        "update_time, deleted)",
        "values (#{parentUuid,jdbcType=VARCHAR}, #{departName,jdbcType=VARCHAR}, ",
        "#{description,jdbcType=VARCHAR}, #{mobile,jdbcType=VARCHAR}, ",
        "#{leaderUuid,jdbcType=VARCHAR}, #{deptAddress,jdbcType=VARCHAR}, ",
        "#{uuid,jdbcType=VARCHAR}, #{createUser,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateUser,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{deleted,jdbcType=BIT})"
    })
    int insert(SysDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..sys_dept
     *
     * @mbg.generated Sat Dec 10 19:13:25 CST 2022
     */
    @InsertProvider(type=SysDeptSqlProvider.class, method="insertSelective")
    int insertSelective(SysDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..sys_dept
     *
     * @mbg.generated Sat Dec 10 19:13:25 CST 2022
     */
    @SelectProvider(type=SysDeptSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="parent_uuid", property="parentUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="depart_name", property="departName", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="mobile", property="mobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="leader_uuid", property="leaderUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="dept_address", property="deptAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="uuid", property="uuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_user", property="createUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_user", property="updateUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="deleted", property="deleted", jdbcType=JdbcType.BIT)
    })
    List<SysDept> selectByExampleWithRowbounds(SysDeptExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..sys_dept
     *
     * @mbg.generated Sat Dec 10 19:13:25 CST 2022
     */
    @SelectProvider(type=SysDeptSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="parent_uuid", property="parentUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="depart_name", property="departName", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="mobile", property="mobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="leader_uuid", property="leaderUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="dept_address", property="deptAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="uuid", property="uuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_user", property="createUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_user", property="updateUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="deleted", property="deleted", jdbcType=JdbcType.BIT)
    })
    List<SysDept> selectByExample(SysDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..sys_dept
     *
     * @mbg.generated Sat Dec 10 19:13:25 CST 2022
     */
    @UpdateProvider(type=SysDeptSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SysDept record, @Param("example") SysDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..sys_dept
     *
     * @mbg.generated Sat Dec 10 19:13:25 CST 2022
     */
    @UpdateProvider(type=SysDeptSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SysDept record, @Param("example") SysDeptExample example);
}