package com.zac.flycloud.dto;

import com.zac.flycloud.basebean.BaseDTO;

public class SysUserDeptDTO extends BaseDTO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flycloud..sys_user_dept.user_uuid
     *
     * @mbg.generated Fri Apr 30 23:29:25 CST 2021
     */
    private String userUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flycloud..sys_user_dept.dept_uuid
     *
     * @mbg.generated Fri Apr 30 23:29:25 CST 2021
     */
    private String deptUuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flycloud..sys_user_dept.user_uuid
     *
     * @return the value of flycloud..sys_user_dept.user_uuid
     *
     * @mbg.generated Fri Apr 30 23:29:25 CST 2021
     */
    public String getUserUuid() {
        return userUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flycloud..sys_user_dept.user_uuid
     *
     * @param userUuid the value for flycloud..sys_user_dept.user_uuid
     *
     * @mbg.generated Fri Apr 30 23:29:25 CST 2021
     */
    public void setUserUuid(String userUuid) {
        this.userUuid = userUuid == null ? null : userUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flycloud..sys_user_dept.dept_uuid
     *
     * @return the value of flycloud..sys_user_dept.dept_uuid
     *
     * @mbg.generated Fri Apr 30 23:29:25 CST 2021
     */
    public String getDeptUuid() {
        return deptUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flycloud..sys_user_dept.dept_uuid
     *
     * @param deptUuid the value for flycloud..sys_user_dept.dept_uuid
     *
     * @mbg.generated Fri Apr 30 23:29:25 CST 2021
     */
    public void setDeptUuid(String deptUuid) {
        this.deptUuid = deptUuid == null ? null : deptUuid.trim();
    }
}