version: '3'
services:
  htx-gateway:
    build:
      context: ./htx-system/htx-gateway
      args:
        - profile
    restart: always
    network_mode: "host"
    ports:
      - 8000:8000
    container_name: htx-gateway
    hostname: htx-gateway
    image: htx-gateway

  htx-auth:
    build:
      context: ./htx-system/htx-auth
      args:
        - profile
    restart: always
    network_mode: "host"
    ports:
      - 8001:8001
    container_name: htx-auth
    hostname: htx-auth
    image: htx-auth

  htx-monitor:
    build:
      context: ./htx-system/htx-monitor
      args:
        - profile
    restart: always
    network_mode: "host"
    ports:
      - 8101:8101
    container_name: htx-monitor
    hostname: htx-monitor
    image: htx-monitor

  htx-admin:
    build:
      context: ./htx-api/htx-admin
      args:
        - profile
    restart: always
    network_mode: "host"
    ports:
      - 8010:8010
    container_name: htx-admin
    hostname: htx-admin
    image: htx-admin
