version: '3'
services:
  zacboot-gateway:
    build:
      context: zacboot-system/zacboot-gateway
      args:
        - profile
    restart: on-failure
    network_mode: "host"
    ports:
      - 8000:8000
    container_name: zacboot-gateway
    hostname: zacboot-gateway
    image: zacboot-gateway

  zacboot-auth:
    build:
      context: zacboot-system/zacboot-auth
      args:
        - profile
    restart: on-failure
    network_mode: "host"
    ports:
      - 8001:8001
    container_name: zacboot-auth
    hostname: zacboot-auth
    image: zacboot-auth

  zacboot-monitor:
    build:
      context: zacboot-system/zacboot-monitor
      args:
        - profile
    restart: on-failure
    network_mode: "host"
    ports:
      - 8101:8101
    container_name: zacboot-monitor
    hostname: zacboot-monitor
    image: zacboot-monitor

  zacboot-admin:
    build:
      context: ./zacboot-api/zacboot-admin
      args:
        - profile
    restart: on-failure
    network_mode: "host"
    ports:
      - 8010:8010
    container_name: zacboot-admin
    hostname: zacboot-admin
    image: zacboot-admin

  zacboot-job:
    build:
      context: ./zacboot-common/zacboot-job
      args:
        - profile
        - xxladd
    restart: on-failure
    network_mode: "host"
    ports:
      - "8066:8066"
    container_name: zacboot-job
    hostname: zacboot-job
    image: zacboot-job
