package com.zac.flycloud.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.zac.flycloud.dto.SysDeptDTO;
import com.zac.flycloud.dto.example.SysDeptDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface SysDeptDTOMapper extends BaseMapper<SysDeptDTO> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flycloud..sys_dept
     *
     * @mbg.generated Fri Apr 30 22:36:02 CST 2021
     */
    @SelectProvider(type=SysDeptDTOSqlProvider.class, method="countByExample")
    long countByExample(SysDeptDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flycloud..sys_dept
     *
     * @mbg.generated Fri Apr 30 22:36:02 CST 2021
     */
    @DeleteProvider(type=SysDeptDTOSqlProvider.class, method="deleteByExample")
    int deleteByExample(SysDeptDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flycloud..sys_dept
     *
     * @mbg.generated Fri Apr 30 22:36:02 CST 2021
     */
    @Insert({
        "insert into sys_dept (uuid, parent_id, ",
        "depart_name, description, ",
        "mobile, fax, address, ",
        "memo, `status`, create_user, ",
        "create_time, update_user, ",
        "update_time, deleted)",
        "values (#{uuid,jdbcType=VARCHAR}, #{parentId,jdbcType=VARCHAR}, ",
        "#{departName,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{mobile,jdbcType=VARCHAR}, #{fax,jdbcType=VARCHAR}, #{address,jdbcType=VARCHAR}, ",
        "#{memo,jdbcType=VARCHAR}, #{status,jdbcType=VARCHAR}, #{createUser,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateUser,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{deleted,jdbcType=BIT})"
    })
    int insert(SysDeptDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flycloud..sys_dept
     *
     * @mbg.generated Fri Apr 30 22:36:02 CST 2021
     */
    @InsertProvider(type=SysDeptDTOSqlProvider.class, method="insertSelective")
    int insertSelective(SysDeptDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flycloud..sys_dept
     *
     * @mbg.generated Fri Apr 30 22:36:02 CST 2021
     */
    @SelectProvider(type=SysDeptDTOSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="uuid", property="uuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="parent_id", property="parentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="depart_name", property="departName", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="mobile", property="mobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="fax", property="fax", jdbcType=JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="memo", property="memo", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_user", property="createUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_user", property="updateUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="deleted", property="deleted", jdbcType=JdbcType.BIT)
    })
    List<SysDeptDTO> selectByExampleWithRowbounds(SysDeptDTOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flycloud..sys_dept
     *
     * @mbg.generated Fri Apr 30 22:36:02 CST 2021
     */
    @SelectProvider(type=SysDeptDTOSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="uuid", property="uuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="parent_id", property="parentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="depart_name", property="departName", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="mobile", property="mobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="fax", property="fax", jdbcType=JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="memo", property="memo", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_user", property="createUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_user", property="updateUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="deleted", property="deleted", jdbcType=JdbcType.BIT)
    })
    List<SysDeptDTO> selectByExample(SysDeptDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flycloud..sys_dept
     *
     * @mbg.generated Fri Apr 30 22:36:02 CST 2021
     */
    @UpdateProvider(type=SysDeptDTOSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SysDeptDTO record, @Param("example") SysDeptDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flycloud..sys_dept
     *
     * @mbg.generated Fri Apr 30 22:36:02 CST 2021
     */
    @UpdateProvider(type=SysDeptDTOSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SysDeptDTO record, @Param("example") SysDeptDTOExample example);
}