package com.zac.flycloud.mapper;

import com.zac.flycloud.dto.SysUserDeptDTO;
import com.zac.flycloud.dto.example.SysUserDeptDTOExample;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface SysUserDeptDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flycloud..sys_user_dept
     *
     * @mbg.generated Fri Apr 30 23:29:25 CST 2021
     */
    @SelectProvider(type=SysUserDeptDTOSqlProvider.class, method="countByExample")
    long countByExample(SysUserDeptDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flycloud..sys_user_dept
     *
     * @mbg.generated Fri Apr 30 23:29:25 CST 2021
     */
    @DeleteProvider(type=SysUserDeptDTOSqlProvider.class, method="deleteByExample")
    int deleteByExample(SysUserDeptDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flycloud..sys_user_dept
     *
     * @mbg.generated Fri Apr 30 23:29:25 CST 2021
     */
    @Insert({
        "insert into sys_user_dept (uuid, user_uuid, ",
        "dept_uuid, create_user, ",
        "create_time, update_user, ",
        "update_time, deleted)",
        "values (#{uuid,jdbcType=VARCHAR}, #{userUuid,jdbcType=VARCHAR}, ",
        "#{deptUuid,jdbcType=VARCHAR}, #{createUser,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateUser,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{deleted,jdbcType=BIT})"
    })
    int insert(SysUserDeptDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flycloud..sys_user_dept
     *
     * @mbg.generated Fri Apr 30 23:29:25 CST 2021
     */
    @InsertProvider(type=SysUserDeptDTOSqlProvider.class, method="insertSelective")
    int insertSelective(SysUserDeptDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flycloud..sys_user_dept
     *
     * @mbg.generated Fri Apr 30 23:29:25 CST 2021
     */
    @SelectProvider(type=SysUserDeptDTOSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="uuid", property="uuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_uuid", property="userUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="dept_uuid", property="deptUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_user", property="createUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_user", property="updateUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="deleted", property="deleted", jdbcType=JdbcType.BIT)
    })
    List<SysUserDeptDTO> selectByExampleWithRowbounds(SysUserDeptDTOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flycloud..sys_user_dept
     *
     * @mbg.generated Fri Apr 30 23:29:25 CST 2021
     */
    @SelectProvider(type=SysUserDeptDTOSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="uuid", property="uuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_uuid", property="userUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="dept_uuid", property="deptUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_user", property="createUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_user", property="updateUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="deleted", property="deleted", jdbcType=JdbcType.BIT)
    })
    List<SysUserDeptDTO> selectByExample(SysUserDeptDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flycloud..sys_user_dept
     *
     * @mbg.generated Fri Apr 30 23:29:25 CST 2021
     */
    @UpdateProvider(type=SysUserDeptDTOSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SysUserDeptDTO record, @Param("example") SysUserDeptDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flycloud..sys_user_dept
     *
     * @mbg.generated Fri Apr 30 23:29:25 CST 2021
     */
    @UpdateProvider(type=SysUserDeptDTOSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SysUserDeptDTO record, @Param("example") SysUserDeptDTOExample example);
}