package com.zac.flycloud.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.zac.flycloud.dto.SysUserRoleDTO;
import com.zac.flycloud.dto.example.SysUserRoleDTOExample;
import java.util.List;

import com.zac.flycloud.tablemodel.SysUserRole;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface SysUserRoleDTOMapper extends BaseMapper<SysUserRoleDTO> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flycloud..sys_user_role
     *
     * @mbg.generated Fri Apr 30 23:30:35 CST 2021
     */
    @SelectProvider(type=SysUserRoleDTOSqlProvider.class, method="countByExample")
    long countByExample(SysUserRoleDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flycloud..sys_user_role
     *
     * @mbg.generated Fri Apr 30 23:30:35 CST 2021
     */
    @DeleteProvider(type=SysUserRoleDTOSqlProvider.class, method="deleteByExample")
    int deleteByExample(SysUserRoleDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flycloud..sys_user_role
     *
     * @mbg.generated Fri Apr 30 23:30:35 CST 2021
     */
    @Insert({
        "insert into sys_user_role (uuid, user_uuid, ",
        "role_uuid, create_user, ",
        "create_time, update_user, ",
        "update_time, deleted)",
        "values (#{uuid,jdbcType=VARCHAR}, #{userUuid,jdbcType=VARCHAR}, ",
        "#{roleUuid,jdbcType=VARCHAR}, #{createUser,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateUser,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{deleted,jdbcType=BIT})"
    })
    int insert(SysUserRoleDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flycloud..sys_user_role
     *
     * @mbg.generated Fri Apr 30 23:30:35 CST 2021
     */
    @InsertProvider(type=SysUserRoleDTOSqlProvider.class, method="insertSelective")
    int insertSelective(SysUserRoleDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flycloud..sys_user_role
     *
     * @mbg.generated Fri Apr 30 23:30:35 CST 2021
     */
    @SelectProvider(type=SysUserRoleDTOSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="uuid", property="uuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_uuid", property="userUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="role_uuid", property="roleUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_user", property="createUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_user", property="updateUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="deleted", property="deleted", jdbcType=JdbcType.BIT)
    })
    List<SysUserRoleDTO> selectByExampleWithRowbounds(SysUserRoleDTOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flycloud..sys_user_role
     *
     * @mbg.generated Fri Apr 30 23:30:35 CST 2021
     */
    @SelectProvider(type=SysUserRoleDTOSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="uuid", property="uuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_uuid", property="userUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="role_uuid", property="roleUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_user", property="createUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_user", property="updateUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="deleted", property="deleted", jdbcType=JdbcType.BIT)
    })
    List<SysUserRoleDTO> selectByExample(SysUserRoleDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flycloud..sys_user_role
     *
     * @mbg.generated Fri Apr 30 23:30:35 CST 2021
     */
    @UpdateProvider(type=SysUserRoleDTOSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SysUserRoleDTO record, @Param("example") SysUserRoleDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flycloud..sys_user_role
     *
     * @mbg.generated Fri Apr 30 23:30:35 CST 2021
     */
    @UpdateProvider(type=SysUserRoleDTOSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SysUserRoleDTO record, @Param("example") SysUserRoleDTOExample example);
}