spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flycloud?useUnicode=true&character_set_server=utf8mb4&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL&allowPublicKeyRetrieval=true
    username: root
    password: mysql417298...
    hikari:
      #最小空闲链接数量
      minimum-idle: 5
      #空闲连接存活最大时间（默认600000）
      idle-timeout: 180000
      #最大连接数
      maximum-pool-size: 10
      #是否自动提交
      auto-commit: true
      #连接池中链接的最长生命周期默认30分钟 = 1800000
      max-lifetime: 1800000
      #链接超时时间
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    ssl: false
    timeout: 3000
  security:
    user:
      name: admin
      password: 918f239c-3a5c-4d74-b0af-4600e5ae7ddc
      roles: admin
  profiles:
    include: common
springfox:
  documentation:
    # prod环境不启用swagger
    enabled: false