debug: false
server:
  port: 8080
spring:
  devtools:
    livereload:
      port: 35730
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fly_cloud?useUnicode=true&characterEncoding=utf8mb4&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: 1234
  redis:
    database: 0
    url: redis://user:@localhost:6379
    host: localhost
    port: 6379
    password:
    ssl: true
    timeout: 3000
  security:
    user:
      name: admin
      password: 918f239c-3a5c-4d74-b0af-4600e5ae7ddc
      roles: admin
# 自定义配置
cus:
  security:
    ignore:
      httpUrls:
        /login,
        /css/**,
        /images/**,
        /js/**