package com.zacboot.admin.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.zacboot.admin.beans.entity.SysPermission;
import com.zacboot.admin.beans.example.SysPermissionExample;
import com.zacboot.admin.mapper.provider.SysPermissionSqlProvider;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface SysPermissionMapper extends BaseMapper<SysPermission> {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated Sun Dec 11 22:51:38 CST 2022
     */
    @SelectProvider(type= SysPermissionSqlProvider.class, method="countByExample")
    long countByExample(SysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated Sun Dec 11 22:51:38 CST 2022
     */
    @DeleteProvider(type= SysPermissionSqlProvider.class, method="deleteByExample")
    int deleteByExample(SysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated Sun Dec 11 22:51:38 CST 2022
     */
    @Insert({
            "insert into sys_permission (`name`, menu_id, ",
            "url_perm, btn_perm, ",
            "gmt_create, gmt_modified)",
            "values (#{name,jdbcType=VARCHAR}, #{menuId,jdbcType=INTEGER}, ",
            "#{urlPerm,jdbcType=VARCHAR}, #{btnPerm,jdbcType=VARCHAR}, ",
            "#{gmtCreate,jdbcType=TIMESTAMP}, #{gmtModified,jdbcType=TIMESTAMP})"
    })
    int insert(SysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated Sun Dec 11 22:51:38 CST 2022
     */
    @InsertProvider(type=SysPermissionSqlProvider.class, method="insertSelective")
    int insertSelective(SysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated Sun Dec 11 22:51:38 CST 2022
     */
    @SelectProvider(type=SysPermissionSqlProvider.class, method="selectByExample")
    @Results({
            @Result(column="name", property="name", jdbcType= JdbcType.VARCHAR),
            @Result(column="menu_id", property="menuId", jdbcType=JdbcType.INTEGER),
            @Result(column="url_perm", property="urlPerm", jdbcType=JdbcType.VARCHAR),
            @Result(column="btn_perm", property="btnPerm", jdbcType=JdbcType.VARCHAR),
            @Result(column="gmt_create", property="gmtCreate", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="gmt_modified", property="gmtModified", jdbcType=JdbcType.TIMESTAMP)
    })
    List<SysPermission> selectByExampleWithRowbounds(SysPermissionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated Sun Dec 11 22:51:38 CST 2022
     */
    @SelectProvider(type=SysPermissionSqlProvider.class, method="selectByExample")
    @Results({
            @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
            @Result(column="menu_id", property="menuId", jdbcType=JdbcType.INTEGER),
            @Result(column="url_perm", property="urlPerm", jdbcType=JdbcType.VARCHAR),
            @Result(column="btn_perm", property="btnPerm", jdbcType=JdbcType.VARCHAR),
            @Result(column="gmt_create", property="gmtCreate", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="gmt_modified", property="gmtModified", jdbcType=JdbcType.TIMESTAMP)
    })
    List<SysPermission> selectByExample(SysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated Sun Dec 11 22:51:38 CST 2022
     */
    @UpdateProvider(type=SysPermissionSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SysPermission record, @Param("example") SysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated Sun Dec 11 22:51:38 CST 2022
     */
    @UpdateProvider(type=SysPermissionSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SysPermission record, @Param("example") SysPermissionExample example);
}
