# 启动脚本环境变量 --spring.profiles.active=home
spring:
  profiles:
    active: dev
  application:
    name: zacboot-admin
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8010