package com.zac.flycloud.bean.dto;

import com.baomidou.mybatisplus.annotation.TableName;
import com.zac.flycloud.bean.basebean.BaseDTO;

@TableName("sys_dept")
public class SysDeptDTO extends BaseDTO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flycloud..sys_dept.parent_id
     *
     * @mbg.generated Fri Apr 30 22:36:02 CST 2021
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flycloud..sys_dept.depart_name
     *
     * @mbg.generated Fri Apr 30 22:36:02 CST 2021
     */
    private String departName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flycloud..sys_dept.description
     *
     * @mbg.generated Fri Apr 30 22:36:02 CST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flycloud..sys_dept.mobile
     *
     * @mbg.generated Fri Apr 30 22:36:02 CST 2021
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flycloud..sys_dept.fax
     *
     * @mbg.generated Fri Apr 30 22:36:02 CST 2021
     */
    private String fax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flycloud..sys_dept.address
     *
     * @mbg.generated Fri Apr 30 22:36:02 CST 2021
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flycloud..sys_dept.memo
     *
     * @mbg.generated Fri Apr 30 22:36:02 CST 2021
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flycloud..sys_dept.status
     *
     * @mbg.generated Fri Apr 30 22:36:02 CST 2021
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flycloud..sys_dept.parent_id
     *
     * @return the value of flycloud..sys_dept.parent_id
     *
     * @mbg.generated Fri Apr 30 22:36:02 CST 2021
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flycloud..sys_dept.parent_id
     *
     * @param parentId the value for flycloud..sys_dept.parent_id
     *
     * @mbg.generated Fri Apr 30 22:36:02 CST 2021
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flycloud..sys_dept.depart_name
     *
     * @return the value of flycloud..sys_dept.depart_name
     *
     * @mbg.generated Fri Apr 30 22:36:02 CST 2021
     */
    public String getDepartName() {
        return departName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flycloud..sys_dept.depart_name
     *
     * @param departName the value for flycloud..sys_dept.depart_name
     *
     * @mbg.generated Fri Apr 30 22:36:02 CST 2021
     */
    public void setDepartName(String departName) {
        this.departName = departName == null ? null : departName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flycloud..sys_dept.description
     *
     * @return the value of flycloud..sys_dept.description
     *
     * @mbg.generated Fri Apr 30 22:36:02 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flycloud..sys_dept.description
     *
     * @param description the value for flycloud..sys_dept.description
     *
     * @mbg.generated Fri Apr 30 22:36:02 CST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flycloud..sys_dept.mobile
     *
     * @return the value of flycloud..sys_dept.mobile
     *
     * @mbg.generated Fri Apr 30 22:36:02 CST 2021
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flycloud..sys_dept.mobile
     *
     * @param mobile the value for flycloud..sys_dept.mobile
     *
     * @mbg.generated Fri Apr 30 22:36:02 CST 2021
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flycloud..sys_dept.fax
     *
     * @return the value of flycloud..sys_dept.fax
     *
     * @mbg.generated Fri Apr 30 22:36:02 CST 2021
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flycloud..sys_dept.fax
     *
     * @param fax the value for flycloud..sys_dept.fax
     *
     * @mbg.generated Fri Apr 30 22:36:02 CST 2021
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flycloud..sys_dept.address
     *
     * @return the value of flycloud..sys_dept.address
     *
     * @mbg.generated Fri Apr 30 22:36:02 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flycloud..sys_dept.address
     *
     * @param address the value for flycloud..sys_dept.address
     *
     * @mbg.generated Fri Apr 30 22:36:02 CST 2021
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flycloud..sys_dept.memo
     *
     * @return the value of flycloud..sys_dept.memo
     *
     * @mbg.generated Fri Apr 30 22:36:02 CST 2021
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flycloud..sys_dept.memo
     *
     * @param memo the value for flycloud..sys_dept.memo
     *
     * @mbg.generated Fri Apr 30 22:36:02 CST 2021
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flycloud..sys_dept.status
     *
     * @return the value of flycloud..sys_dept.status
     *
     * @mbg.generated Fri Apr 30 22:36:02 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flycloud..sys_dept.status
     *
     * @param status the value for flycloud..sys_dept.status
     *
     * @mbg.generated Fri Apr 30 22:36:02 CST 2021
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}