package com.zac.flycloud.bean.dto;

import com.baomidou.mybatisplus.annotation.TableName;
import com.zac.flycloud.bean.basebean.BaseDTO;

@TableName("sys_log")
public class SysLogDTO extends BaseDTO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flycloud..sys_log.cost_time
     *
     * @mbg.generated Sat Apr 24 19:05:51 CST 2021
     */
    private Long costTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flycloud..sys_log.ip
     *
     * @mbg.generated Sat Apr 24 19:05:51 CST 2021
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flycloud..sys_log.request_param
     *
     * @mbg.generated Sat Apr 24 19:05:51 CST 2021
     */
    private String requestParam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flycloud..sys_log.request_type
     *
     * @mbg.generated Sat Apr 24 19:05:51 CST 2021
     */
    private String requestType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flycloud..sys_log.request_url
     *
     * @mbg.generated Sat Apr 24 19:05:51 CST 2021
     */
    private String requestUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flycloud..sys_log.method
     *
     * @mbg.generated Sat Apr 24 19:05:51 CST 2021
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flycloud..sys_log.username
     *
     * @mbg.generated Sat Apr 24 19:05:51 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flycloud..sys_log.userid
     *
     * @mbg.generated Sat Apr 24 19:05:51 CST 2021
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flycloud..sys_log.log_content
     *
     * @mbg.generated Sat Apr 24 19:05:51 CST 2021
     */
    private String logContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flycloud..sys_log.log_type
     *
     * @mbg.generated Sat Apr 24 19:05:51 CST 2021
     */
    private Integer logType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flycloud..sys_log.operate_type
     *
     * @mbg.generated Sat Apr 24 19:05:51 CST 2021
     */
    private Integer operateType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flycloud..sys_log.cost_time
     *
     * @return the value of flycloud..sys_log.cost_time
     *
     * @mbg.generated Sat Apr 24 19:05:51 CST 2021
     */
    public Long getCostTime() {
        return costTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flycloud..sys_log.cost_time
     *
     * @param costTime the value for flycloud..sys_log.cost_time
     *
     * @mbg.generated Sat Apr 24 19:05:51 CST 2021
     */
    public void setCostTime(Long costTime) {
        this.costTime = costTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flycloud..sys_log.ip
     *
     * @return the value of flycloud..sys_log.ip
     *
     * @mbg.generated Sat Apr 24 19:05:51 CST 2021
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flycloud..sys_log.ip
     *
     * @param ip the value for flycloud..sys_log.ip
     *
     * @mbg.generated Sat Apr 24 19:05:51 CST 2021
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flycloud..sys_log.request_param
     *
     * @return the value of flycloud..sys_log.request_param
     *
     * @mbg.generated Sat Apr 24 19:05:51 CST 2021
     */
    public String getRequestParam() {
        return requestParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flycloud..sys_log.request_param
     *
     * @param requestParam the value for flycloud..sys_log.request_param
     *
     * @mbg.generated Sat Apr 24 19:05:51 CST 2021
     */
    public void setRequestParam(String requestParam) {
        this.requestParam = requestParam == null ? null : requestParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flycloud..sys_log.request_type
     *
     * @return the value of flycloud..sys_log.request_type
     *
     * @mbg.generated Sat Apr 24 19:05:51 CST 2021
     */
    public String getRequestType() {
        return requestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flycloud..sys_log.request_type
     *
     * @param requestType the value for flycloud..sys_log.request_type
     *
     * @mbg.generated Sat Apr 24 19:05:51 CST 2021
     */
    public void setRequestType(String requestType) {
        this.requestType = requestType == null ? null : requestType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flycloud..sys_log.request_url
     *
     * @return the value of flycloud..sys_log.request_url
     *
     * @mbg.generated Sat Apr 24 19:05:51 CST 2021
     */
    public String getRequestUrl() {
        return requestUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flycloud..sys_log.request_url
     *
     * @param requestUrl the value for flycloud..sys_log.request_url
     *
     * @mbg.generated Sat Apr 24 19:05:51 CST 2021
     */
    public void setRequestUrl(String requestUrl) {
        this.requestUrl = requestUrl == null ? null : requestUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flycloud..sys_log.method
     *
     * @return the value of flycloud..sys_log.method
     *
     * @mbg.generated Sat Apr 24 19:05:51 CST 2021
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flycloud..sys_log.method
     *
     * @param method the value for flycloud..sys_log.method
     *
     * @mbg.generated Sat Apr 24 19:05:51 CST 2021
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flycloud..sys_log.username
     *
     * @return the value of flycloud..sys_log.username
     *
     * @mbg.generated Sat Apr 24 19:05:51 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flycloud..sys_log.username
     *
     * @param username the value for flycloud..sys_log.username
     *
     * @mbg.generated Sat Apr 24 19:05:51 CST 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flycloud..sys_log.userid
     *
     * @return the value of flycloud..sys_log.userid
     *
     * @mbg.generated Sat Apr 24 19:05:51 CST 2021
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flycloud..sys_log.userid
     *
     * @param userid the value for flycloud..sys_log.userid
     *
     * @mbg.generated Sat Apr 24 19:05:51 CST 2021
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flycloud..sys_log.log_content
     *
     * @return the value of flycloud..sys_log.log_content
     *
     * @mbg.generated Sat Apr 24 19:05:51 CST 2021
     */
    public String getLogContent() {
        return logContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flycloud..sys_log.log_content
     *
     * @param logContent the value for flycloud..sys_log.log_content
     *
     * @mbg.generated Sat Apr 24 19:05:51 CST 2021
     */
    public void setLogContent(String logContent) {
        this.logContent = logContent == null ? null : logContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flycloud..sys_log.log_type
     *
     * @return the value of flycloud..sys_log.log_type
     *
     * @mbg.generated Sat Apr 24 19:05:51 CST 2021
     */
    public Integer getLogType() {
        return logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flycloud..sys_log.log_type
     *
     * @param logType the value for flycloud..sys_log.log_type
     *
     * @mbg.generated Sat Apr 24 19:05:51 CST 2021
     */
    public void setLogType(Integer logType) {
        this.logType = logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flycloud..sys_log.operate_type
     *
     * @return the value of flycloud..sys_log.operate_type
     *
     * @mbg.generated Sat Apr 24 19:05:51 CST 2021
     */
    public Integer getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flycloud..sys_log.operate_type
     *
     * @param operateType the value for flycloud..sys_log.operate_type
     *
     * @mbg.generated Sat Apr 24 19:05:51 CST 2021
     */
    public void setOperateType(Integer operateType) {
        this.operateType = operateType;
    }
}