package com.zac.flycloud.bean.dto;

import com.baomidou.mybatisplus.annotation.TableName;
import com.zac.flycloud.bean.basebean.BaseDTO;

@TableName("sys_role")
public class SysRoleDTO extends BaseDTO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flycloud..sys_role.role_name
     *
     * @mbg.generated Fri Apr 30 23:19:11 CST 2021
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flycloud..sys_role.role_code
     *
     * @mbg.generated Fri Apr 30 23:19:11 CST 2021
     */
    private String roleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flycloud..sys_role.description
     *
     * @mbg.generated Fri Apr 30 23:19:11 CST 2021
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flycloud..sys_role.role_name
     *
     * @return the value of flycloud..sys_role.role_name
     *
     * @mbg.generated Fri Apr 30 23:19:11 CST 2021
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flycloud..sys_role.role_name
     *
     * @param roleName the value for flycloud..sys_role.role_name
     *
     * @mbg.generated Fri Apr 30 23:19:11 CST 2021
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flycloud..sys_role.role_code
     *
     * @return the value of flycloud..sys_role.role_code
     *
     * @mbg.generated Fri Apr 30 23:19:11 CST 2021
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flycloud..sys_role.role_code
     *
     * @param roleCode the value for flycloud..sys_role.role_code
     *
     * @mbg.generated Fri Apr 30 23:19:11 CST 2021
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flycloud..sys_role.description
     *
     * @return the value of flycloud..sys_role.description
     *
     * @mbg.generated Fri Apr 30 23:19:11 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flycloud..sys_role.description
     *
     * @param description the value for flycloud..sys_role.description
     *
     * @mbg.generated Fri Apr 30 23:19:11 CST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}