package com.zac.flycloud.start.bean.dtos;

import cn.hutool.core.bean.BeanUtil;
import com.zac.flycloud.start.bean.basebean.BaseDTO;
import com.zac.flycloud.start.bean.entity.SysUser;
import lombok.Data;

@Data
public class SysUserDTO extends BaseDTO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flycloud..sys_user.username
     *
     * @mbg.generated Sat Apr 24 17:24:37 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flycloud..sys_user.password
     *
     * @mbg.generated Sat Apr 24 17:24:37 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flycloud..sys_user.realname
     *
     * @mbg.generated Sat Apr 24 17:24:37 CST 2021
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flycloud..sys_user.avatar
     *
     * @mbg.generated Sat Apr 24 17:24:37 CST 2021
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flycloud..sys_user.nickname
     *
     * @mbg.generated Sat Apr 24 17:24:37 CST 2021
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flycloud..sys_user.mail
     *
     * @mbg.generated Sat Apr 24 17:24:37 CST 2021
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flycloud..sys_user.phone
     *
     * @mbg.generated Sat Apr 24 17:24:37 CST 2021
     */
    private String phone;

    public SysUserDTO(SysUser sysUser){
        BeanUtil.copyProperties(sysUser,this);
    }
}