package com.zac.flycloud.start.bean.dtos;

import com.zac.flycloud.start.bean.basebean.BaseDTO;
import lombok.Data;

@Data
public class SysUserRoleDTO extends BaseDTO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flycloud..sys_user_role.user_uuid
     *
     * @mbg.generated Fri Apr 30 23:30:35 CST 2021
     */
    private String userUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flycloud..sys_user_role.role_uuid
     *
     * @mbg.generated Fri Apr 30 23:30:35 CST 2021
     */
    private String roleUuid;

}