package com.zacboot.admin.property.mapper;

import java.util.List;
import java.util.Map;

import com.zacboot.admin.property.dto.example.AppPropertyExample;
import com.zacboot.system.core.entity.administration.AppProperty;
import org.apache.ibatis.jdbc.SQL;

public class AppPropertySqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_property
     *
     * @mbg.generated Wed Apr 26 16:20:54 CST 2023
     */
    public String countByExample(AppPropertyExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("app_property");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_property
     *
     * @mbg.generated Wed Apr 26 16:20:54 CST 2023
     */
    public String deleteByExample(AppPropertyExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("app_property");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_property
     *
     * @mbg.generated Wed Apr 26 16:20:54 CST 2023
     */
    public String insertSelective(AppProperty record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("app_property");
        
        if (record.getUuid() != null) {
            sql.VALUES("uuid", "#{uuid,jdbcType=VARCHAR}");
        }
        
        if (record.getPropertyNo() != null) {
            sql.VALUES("property_no", "#{propertyNo,jdbcType=VARCHAR}");
        }
        
        if (record.getPropertyName() != null) {
            sql.VALUES("property_name", "#{propertyName,jdbcType=VARCHAR}");
        }
        
        if (record.getPrice() != null) {
            sql.VALUES("price", "#{price,jdbcType=DECIMAL}");
        }
        
        if (record.getUseTotalCount() != null) {
            sql.VALUES("use_total_count", "#{useTotalCount,jdbcType=INTEGER}");
        }
        
        if (record.getRemainCount() != null) {
            sql.VALUES("remain_count", "#{remainCount,jdbcType=INTEGER}");
        }
        
        if (record.getSpecModel() != null) {
            sql.VALUES("spec_model", "#{specModel,jdbcType=VARCHAR}");
        }
        
        if (record.getBuyDate() != null) {
            sql.VALUES("buy_date", "#{buyDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUseDate() != null) {
            sql.VALUES("use_date", "#{useDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getTypeCode() != null) {
            sql.VALUES("type_code", "#{typeCode,jdbcType=VARCHAR}");
        }
        
        if (record.getUseDeptUuid() != null) {
            sql.VALUES("use_dept_uuid", "#{useDeptUuid,jdbcType=VARCHAR}");
        }
        
        if (record.getUseDeptName() != null) {
            sql.VALUES("use_dept_name", "#{useDeptName,jdbcType=VARCHAR}");
        }
        
        if (record.getOwnerUuid() != null) {
            sql.VALUES("owner_uuid", "#{ownerUuid,jdbcType=VARCHAR}");
        }
        
        if (record.getOwnerName() != null) {
            sql.VALUES("owner_name", "#{ownerName,jdbcType=VARCHAR}");
        }
        
        if (record.getLocation() != null) {
            sql.VALUES("`location`", "#{location,jdbcType=VARCHAR}");
        }
        
        if (record.getRemark() != null) {
            sql.VALUES("remark", "#{remark,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateUser() != null) {
            sql.VALUES("create_user", "#{createUser,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateUser() != null) {
            sql.VALUES("update_user", "#{updateUser,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.VALUES("update_time", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getDeleted() != null) {
            sql.VALUES("deleted", "#{deleted,jdbcType=BIT}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_property
     *
     * @mbg.generated Wed Apr 26 16:20:54 CST 2023
     */
    public String selectByExample(AppPropertyExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("uuid");
        } else {
            sql.SELECT("uuid");
        }
        sql.SELECT("property_no");
        sql.SELECT("property_name");
        sql.SELECT("price");
        sql.SELECT("use_total_count");
        sql.SELECT("remain_count");
        sql.SELECT("spec_model");
        sql.SELECT("buy_date");
        sql.SELECT("use_date");
        sql.SELECT("type_code");
        sql.SELECT("use_dept_uuid");
        sql.SELECT("use_dept_name");
        sql.SELECT("owner_uuid");
        sql.SELECT("owner_name");
        sql.SELECT("`location`");
        sql.SELECT("remark");
        sql.SELECT("create_user");
        sql.SELECT("create_time");
        sql.SELECT("update_user");
        sql.SELECT("update_time");
        sql.SELECT("deleted");
        sql.FROM("app_property");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_property
     *
     * @mbg.generated Wed Apr 26 16:20:54 CST 2023
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        AppProperty record = (AppProperty) parameter.get("record");
        AppPropertyExample example = (AppPropertyExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("app_property");
        
        if (record.getUuid() != null) {
            sql.SET("uuid = #{record.uuid,jdbcType=VARCHAR}");
        }
        
        if (record.getPropertyNo() != null) {
            sql.SET("property_no = #{record.propertyNo,jdbcType=VARCHAR}");
        }
        
        if (record.getPropertyName() != null) {
            sql.SET("property_name = #{record.propertyName,jdbcType=VARCHAR}");
        }
        
        if (record.getPrice() != null) {
            sql.SET("price = #{record.price,jdbcType=DECIMAL}");
        }
        
        if (record.getUseTotalCount() != null) {
            sql.SET("use_total_count = #{record.useTotalCount,jdbcType=INTEGER}");
        }
        
        if (record.getRemainCount() != null) {
            sql.SET("remain_count = #{record.remainCount,jdbcType=INTEGER}");
        }
        
        if (record.getSpecModel() != null) {
            sql.SET("spec_model = #{record.specModel,jdbcType=VARCHAR}");
        }
        
        if (record.getBuyDate() != null) {
            sql.SET("buy_date = #{record.buyDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUseDate() != null) {
            sql.SET("use_date = #{record.useDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getTypeCode() != null) {
            sql.SET("type_code = #{record.typeCode,jdbcType=VARCHAR}");
        }
        
        if (record.getUseDeptUuid() != null) {
            sql.SET("use_dept_uuid = #{record.useDeptUuid,jdbcType=VARCHAR}");
        }
        
        if (record.getUseDeptName() != null) {
            sql.SET("use_dept_name = #{record.useDeptName,jdbcType=VARCHAR}");
        }
        
        if (record.getOwnerUuid() != null) {
            sql.SET("owner_uuid = #{record.ownerUuid,jdbcType=VARCHAR}");
        }
        
        if (record.getOwnerName() != null) {
            sql.SET("owner_name = #{record.ownerName,jdbcType=VARCHAR}");
        }
        
        if (record.getLocation() != null) {
            sql.SET("`location` = #{record.location,jdbcType=VARCHAR}");
        }
        
        if (record.getRemark() != null) {
            sql.SET("remark = #{record.remark,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateUser() != null) {
            sql.SET("create_user = #{record.createUser,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateUser() != null) {
            sql.SET("update_user = #{record.updateUser,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getDeleted() != null) {
            sql.SET("deleted = #{record.deleted,jdbcType=BIT}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_property
     *
     * @mbg.generated Wed Apr 26 16:20:54 CST 2023
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("app_property");
        
        sql.SET("uuid = #{record.uuid,jdbcType=VARCHAR}");
        sql.SET("property_no = #{record.propertyNo,jdbcType=VARCHAR}");
        sql.SET("property_name = #{record.propertyName,jdbcType=VARCHAR}");
        sql.SET("price = #{record.price,jdbcType=DECIMAL}");
        sql.SET("use_total_count = #{record.useTotalCount,jdbcType=INTEGER}");
        sql.SET("remain_count = #{record.remainCount,jdbcType=INTEGER}");
        sql.SET("spec_model = #{record.specModel,jdbcType=VARCHAR}");
        sql.SET("buy_date = #{record.buyDate,jdbcType=TIMESTAMP}");
        sql.SET("use_date = #{record.useDate,jdbcType=TIMESTAMP}");
        sql.SET("type_code = #{record.typeCode,jdbcType=VARCHAR}");
        sql.SET("use_dept_uuid = #{record.useDeptUuid,jdbcType=VARCHAR}");
        sql.SET("use_dept_name = #{record.useDeptName,jdbcType=VARCHAR}");
        sql.SET("owner_uuid = #{record.ownerUuid,jdbcType=VARCHAR}");
        sql.SET("owner_name = #{record.ownerName,jdbcType=VARCHAR}");
        sql.SET("`location` = #{record.location,jdbcType=VARCHAR}");
        sql.SET("remark = #{record.remark,jdbcType=VARCHAR}");
        sql.SET("create_user = #{record.createUser,jdbcType=VARCHAR}");
        sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        sql.SET("update_user = #{record.updateUser,jdbcType=VARCHAR}");
        sql.SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        sql.SET("deleted = #{record.deleted,jdbcType=BIT}");
        
        AppPropertyExample example = (AppPropertyExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_property
     *
     * @mbg.generated Wed Apr 26 16:20:54 CST 2023
     */
    protected void applyWhere(SQL sql, AppPropertyExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<AppPropertyExample.Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            AppPropertyExample.Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<AppPropertyExample.Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    AppPropertyExample.Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}