spring:
  datasource:
    redis:
      database: 0
      port: 6379
      host: 127.0.0.1
      password:
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
      config:
        server-addr: http://localhost:8848
        file-extension: yaml
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: zacboot-auth
          uri: lb://zacboot-system-sso
          predicates:
            - Path=/api-auth/**
          filters:
            - StripPrefix=1
        - id: zacboot-admin
          uri: lb://zacboot-admin
          predicates:
            - Path=/api-admin/**
          filters:
            - StripPrefix=1
        - id: zacboot-app
          uri: lb://zacboot-app-user
          predicates:
            - Path=/api-app/**
          filters:
            - StripPrefix=1
        - id: zacboot-admin-work
          uri: lb://zacboot-admin-work
          predicates:
            - Path=/api-admin-work/work/**
          filters:
            - StripPrefix=2
  config:
    import: application-common.yml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  level:
    root: info
    com.zacboot.system: debug
logstash:
  host: localhost