server:
  port: 8008
spring:
  profiles:
    active: @profiles.active@
  application:
    name: @artifactId@
  cloud:
    nacos:
      config:
        server-addr: @nacos.config.server-addr@
        namespace: zacboot
  config:
    import:
      - optional:nacos:zacboot-common.yml
      - optional:nacos:${spring.application.name}.yml
logging:
  level:
    root: debug