server:
  port: 8900
spring:
  application:
    name: fly-cloud
  devtools:
    livereload:
      #指定热加载端口，防止多个springboot项目同时启动热部署的话造成端口占用
      port: 35730
  output:
    ansi:
      enabled: always
  main:
    allow-circular-references: true
# mybatis代码生成器相关配置
mybatis:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath*:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.zac.flycloud.bean.tablemodel
  configuration:
    # 设置下划线和驼峰转换
    map-underscore-to-camel-case: true
#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      # 默认数据库表下划线命名
      table-underline: true
      #主键类型
      id-type: auto
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true
# 自定义配置
flycloud:
  security:
    ignore:
      httpUrls:
        /css/**, /images/**, /img/**, /js/**,
        /swagger-ui.html, /swagger-ui/**, /swagger-resources, /swagger-resources/**, /v2/api-docs, /v3/api-docs,
        /webjars/**, /index, /api/sys/**, /api/mybatisGenerator/**
    tokenKey: 644b18e4eade56810e649357597aa3b0
    sysToken: flycloud-88888888-token
    swaggerUser: flycloud
  actable:
    # 需要自动建表的包名
    pack: com.zac.flycloud.bean.tablemodel
    primarykey: id
    tableAuto: update
    # ElasticSearch 6设置
  elasticsearch:
    cluster-name: elasticsearch
    cluster-nodes: 127.0.0.1:9200
    check-enabled: false
    # OSS_ALI_CLIENT / OSS_TENCENT_CLIENT
  uploadClient: OSS_ALI_CLIENT
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKey: ??
    secretKey: ??
    bucketName: flycloudos
    staticDomain: https://static.flycloud.com