package com.zacboot.system.core.entity.assess;

import com.baomidou.mybatisplus.annotation.TableName;
import com.zacboot.system.core.entity.BaseEntity;
import lombok.Data;

import java.util.Date;

/**
 * 考核申诉
 */
@Data
@TableName("app_assess_appeal")
public class AppAssessAppeal extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zacboot..app_assess_appeal.user_uuid
     *
     * @mbg.generated Thu Apr 20 15:11:15 CST 2023
     */
    private String userUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zacboot..app_assess_appeal.user_name
     *
     * @mbg.generated Thu Apr 20 15:11:15 CST 2023
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zacboot..app_assess_appeal.dept_uuid
     *
     * @mbg.generated Thu Apr 20 15:11:15 CST 2023
     */
    private String deptUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zacboot..app_assess_appeal.dept_name
     *
     * @mbg.generated Thu Apr 20 15:11:15 CST 2023
     */
    private String deptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zacboot..app_assess_appeal.role_uuid
     *
     * @mbg.generated Thu Apr 20 15:11:15 CST 2023
     */
    private String roleUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zacboot..app_assess_appeal.role_name
     *
     * @mbg.generated Thu Apr 20 15:11:15 CST 2023
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zacboot..app_assess_appeal.appeal_text
     *
     * @mbg.generated Thu Apr 20 15:11:15 CST 2023
     */
    private String appealText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zacboot..app_assess_appeal.receiver_uuid
     *
     * @mbg.generated Thu Apr 20 15:11:15 CST 2023
     */
    private String receiverUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zacboot..app_assess_appeal.receiver_name
     *
     * @mbg.generated Thu Apr 20 15:11:15 CST 2023
     */
    private String receiverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zacboot..app_assess_appeal.appeal_date
     *
     * @mbg.generated Thu Apr 20 15:11:15 CST 2023
     */
    private Date appealDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zacboot..app_assess_appeal.face_talk_date
     *
     * @mbg.generated Thu Apr 20 15:11:15 CST 2023
     */
    private Date faceTalkDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zacboot..app_assess_appeal.handle_by
     *
     * @mbg.generated Thu Apr 20 15:11:15 CST 2023
     */
    private String handleBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zacboot..app_assess_appeal.remark
     *
     * @mbg.generated Thu Apr 20 15:11:15 CST 2023
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zacboot..app_assess_appeal.appeal_detail
     *
     * @mbg.generated Thu Apr 20 15:11:15 CST 2023
     */
    private String appealDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zacboot..app_assess_appeal.examine
     *
     * @mbg.generated Thu Apr 20 15:11:15 CST 2023
     */
    private String examine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zacboot..app_assess_appeal.solution
     *
     * @mbg.generated Thu Apr 20 15:11:15 CST 2023
     */
    private String solution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zacboot..app_assess_appeal.coord_results
     *
     * @mbg.generated Thu Apr 20 15:11:15 CST 2023
     */
    private String coordResults;
}