package com.zacboot.system.core.entity.assess;

import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.zacboot.system.core.entity.BaseEntity;
import lombok.Data;

import java.util.Date;
import java.util.TimeZone;

@Data
@TableName("app_three_report")
public class AppThreeReport extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zacboot..app_three_report.user_uuid
     *
     * @mbg.generated Thu Apr 20 15:06:52 CST 2023
     */
    private String userUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zacboot..app_three_report.user_name
     *
     * @mbg.generated Thu Apr 20 15:06:52 CST 2023
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zacboot..app_three_report.dept_uuid
     *
     * @mbg.generated Thu Apr 20 15:06:52 CST 2023
     */
    private String deptUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zacboot..app_three_report.dept_name
     *
     * @mbg.generated Thu Apr 20 15:06:52 CST 2023
     */
    private String deptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zacboot..app_three_report.role_uuid
     *
     * @mbg.generated Thu Apr 20 15:06:52 CST 2023
     */
    private String roleUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zacboot..app_three_report.role_name
     *
     * @mbg.generated Thu Apr 20 15:06:52 CST 2023
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zacboot..app_three_report.report_type
     *
     * @mbg.generated Thu Apr 20 15:06:52 CST 2023
     */
    private String reportType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zacboot..app_three_report.start_date
     *
     * @mbg.generated Thu Apr 20 15:06:52 CST 2023
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zacboot..app_three_report.end_date
     *
     * @mbg.generated Thu Apr 20 15:06:52 CST 2023
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zacboot..app_three_report.final
     *
     * @mbg.generated Thu Apr 20 15:06:52 CST 2023
     */
    private Integer complete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zacboot..app_three_report.work_content
     *
     * @mbg.generated Thu Apr 20 15:06:52 CST 2023
     */
    private String workContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zacboot..app_three_report.unfinal_reason
     *
     * @mbg.generated Thu Apr 20 15:06:52 CST 2023
     */
    private String unfinalReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zacboot..app_three_report.difficulty
     *
     * @mbg.generated Thu Apr 20 15:06:52 CST 2023
     */
    private String difficulty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zacboot..app_three_report.todo_list
     *
     * @mbg.generated Thu Apr 20 15:06:52 CST 2023
     */
    private String todoList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zacboot..app_three_report.future_plans
     *
     * @mbg.generated Thu Apr 20 15:06:52 CST 2023
     */
    private String futurePlans;
}