package com.zacboot.admin.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.zacboot.core.entity.admin.SysDept;
import com.zacboot.core.entity.admin.SysUser;
import com.zacboot.core.entity.admin.SysUserDept;
import com.zacboot.admin.beans.example.SysUserDeptExample;
import com.zacboot.admin.mapper.provider.SysUserDeptDTOSqlProvider;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface SysUserDeptMapper extends BaseMapper<SysUserDept>{

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table zacboot..sys_user_dept
	 *
	 * @mbg.generated Fri Apr 30 23:29:25 CST 2021
	 */
	@SelectProvider(type= SysUserDeptDTOSqlProvider.class, method="countByExample")
	long countByExample(SysUserDeptExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table zacboot..sys_user_dept
	 *
	 * @mbg.generated Fri Apr 30 23:29:25 CST 2021
	 */
	@DeleteProvider(type=SysUserDeptDTOSqlProvider.class, method="deleteByExample")
	int deleteByExample(SysUserDeptExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table zacboot..sys_user_dept
	 *
	 * @mbg.generated Fri Apr 30 23:29:25 CST 2021
	 */
	int insert(SysUserDept record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table zacboot..sys_user_dept
	 *
	 * @mbg.generated Fri Apr 30 23:29:25 CST 2021
	 */
	@InsertProvider(type=SysUserDeptDTOSqlProvider.class, method="insertSelective")
	int insertSelective(SysUserDept record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table zacboot..sys_user_dept
	 *
	 * @mbg.generated Fri Apr 30 23:29:25 CST 2021
	 */
	@SelectProvider(type=SysUserDeptDTOSqlProvider.class, method="selectByExample")
	@Results({
			@Result(column="uuid", property="uuid", jdbcType= JdbcType.VARCHAR),
			@Result(column="user_uuid", property="userUuid", jdbcType=JdbcType.VARCHAR),
			@Result(column="dept_uuid", property="deptUuid", jdbcType=JdbcType.VARCHAR),
			@Result(column="create_user", property="createUser", jdbcType=JdbcType.VARCHAR),
			@Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
			@Result(column="update_user", property="updateUser", jdbcType=JdbcType.VARCHAR),
			@Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
			@Result(column="deleted", property="deleted", jdbcType=JdbcType.BIT)
	})
	List<SysUserDept> selectByExampleWithRowbounds(SysUserDeptExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table zacboot..sys_user_dept
	 *
	 * @mbg.generated Fri Apr 30 23:29:25 CST 2021
	 */
	@SelectProvider(type=SysUserDeptDTOSqlProvider.class, method="selectByExample")
	@Results({
			@Result(column="uuid", property="uuid", jdbcType=JdbcType.VARCHAR),
			@Result(column="user_uuid", property="userUuid", jdbcType=JdbcType.VARCHAR),
			@Result(column="dept_uuid", property="deptUuid", jdbcType=JdbcType.VARCHAR),
			@Result(column="create_user", property="createUser", jdbcType=JdbcType.VARCHAR),
			@Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
			@Result(column="update_user", property="updateUser", jdbcType=JdbcType.VARCHAR),
			@Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
			@Result(column="deleted", property="deleted", jdbcType=JdbcType.BIT)
	})
	List<SysUserDept> selectByExample(SysUserDeptExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table zacboot..sys_user_dept
	 *
	 * @mbg.generated Fri Apr 30 23:29:25 CST 2021
	 */
	@UpdateProvider(type=SysUserDeptDTOSqlProvider.class, method="updateByExampleSelective")
	int updateByExampleSelective(@Param("record") SysUserDept record, @Param("example") SysUserDeptExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table zacboot..sys_user_dept
	 *
	 * @mbg.generated Fri Apr 30 23:29:25 CST 2021
	 */
	@UpdateProvider(type=SysUserDeptDTOSqlProvider.class, method="updateByExample")
	int updateByExample(@Param("record") SysUserDept record, @Param("example") SysUserDeptExample example);

	/**
	 * 根据用户uuid获取所属部门列表
	 * @param userUuid
	 * @return
	 */
	@Select("select * from sys_dept	where uuid in (select dept_uuid from sys_user_dept where user_uuid = #{userUuid})")
	List<SysDept> getDeptsByUserUuid(@Param("userUuid") String userUuid);

	/**
	 * 根据部门uuid获取部门员工列表
	 * @param deptUuid
	 * @return
	 */
	@Select("select * from sys_user	where uuid in (select user_uuid from sys_user_dept where dept_uuid = #{deptUuid})")
	List<SysUser> getUsersByDeptUuid(@Param("deptUuid") String deptUuid);

}
