server:
  port: 8000
spring:
  profiles:
    active: @profiles.active@
  application:
    name: @artifactId@
  cloud:
    nacos:
      config:
        server-addr: @nacos.config.server-addr@
        group: @nacos.config.group@
        file-extension: yaml
        namespace: zacboot
      discovery:
        server-addr: @nacos.config.server-addr@
        namespace: zacboot
        watch:
          enabled: true
  config:
    import:
      - optional:nacos:zacboot-common.yml
      - optional:nacos:${spring.application.name}.yml
  main:
    web-application-type: reactive