spring:
  application:
    name: @artifactId@
  security: # 配置登录用户名和密码
    user:
      name: admin
      password: 123456
  boot:  # 不显示admin-server的监控信息
    admin:
      discovery:
        ignored-services: ${spring.application.name}
  cloud:
    nacos:
      config:
        server-addr: @nacos.config.server-addr@
        namespace: zacboot
      discovery:
        server-addr: @nacos.config.server-addr@
        namespace: zacboot
  config:
    import: optional:nacos:zacboot-common.yml
server:
  port: 8101
