spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3336/htx-admin?useUnicode=true&character_set_server=utf8mb4&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL&allowPublicKeyRetrieval=true
    username: root
    password: mysql417298...
    hikari:
      #最小空闲链接数量
      minimum-idle: 5
      #空闲连接存活最大时间（默认600000）
      idle-timeout: 180000
      #最大连接数
      maximum-pool-size: 10
      #是否自动提交
      auto-commit: true
      #连接池中链接的最长生命周期默认30分钟 = 1800000
      max-lifetime: 1800000
      #链接超时时间
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    ssl: false
    timeout: 3000
  security:
    user:
      name: admin
      password: 918f239c-3a5c-4d74-b0af-4600e5ae7ddc
      roles: admin
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: @nacos.config.server-addr@
      config:
        server-addr: @nacos.config.server-addr@
  config:
    import:
      - optional:nacos:htx-common.yml
xxl:
  job:
    admin:
      # 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
      address: http://htxalitest.lcago.cn:8080/xxl-job-admin
    executor:
      appname: xxljob-${spring.application.name}-executor
      # 执行器端口号，单机部署多个执行器时，注意要配置不同执行器端口；
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      # 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
      logretentiondays: 7
