# 启动脚本环境变量 --spring.profiles.active=home
spring:
  profiles:
    active: dev
  application:
    name: htx-admin
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    livereload:
      port: 35722
  main:
    allow-circular-references: true
server:
  port: 8010