package com.zacboot.admin.work.mapper.provider;

import com.zacboot.admin.work.beans.example.AppAssessAppealExample;
import com.zacboot.system.core.entity.admin.AppAssessAppeal;
import org.apache.ibatis.jdbc.SQL;

import java.util.List;
import java.util.Map;

public class AppAssessAppealSqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_assess_appeal
     *
     * @mbg.generated Thu Apr 20 15:24:08 CST 2023
     */
    public String countByExample(AppAssessAppealExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("app_assess_appeal");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_assess_appeal
     *
     * @mbg.generated Thu Apr 20 15:24:08 CST 2023
     */
    public String deleteByExample(AppAssessAppealExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("app_assess_appeal");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_assess_appeal
     *
     * @mbg.generated Thu Apr 20 15:24:08 CST 2023
     */
    public String insertSelective(AppAssessAppeal record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("app_assess_appeal");
        
        if (record.getUuid() != null) {
            sql.VALUES("uuid", "#{uuid,jdbcType=VARCHAR}");
        }
        
        if (record.getUserUuid() != null) {
            sql.VALUES("user_uuid", "#{userUuid,jdbcType=VARCHAR}");
        }
        
        if (record.getUserName() != null) {
            sql.VALUES("user_name", "#{userName,jdbcType=VARCHAR}");
        }
        
        if (record.getDeptUuid() != null) {
            sql.VALUES("dept_uuid", "#{deptUuid,jdbcType=VARCHAR}");
        }
        
        if (record.getDeptName() != null) {
            sql.VALUES("dept_name", "#{deptName,jdbcType=VARCHAR}");
        }
        
        if (record.getRoleUuid() != null) {
            sql.VALUES("role_uuid", "#{roleUuid,jdbcType=VARCHAR}");
        }
        
        if (record.getRoleName() != null) {
            sql.VALUES("role_name", "#{roleName,jdbcType=VARCHAR}");
        }
        
        if (record.getAppealText() != null) {
            sql.VALUES("appeal_text", "#{appealText,jdbcType=VARCHAR}");
        }
        
        if (record.getReceiverUuid() != null) {
            sql.VALUES("receiver_uuid", "#{receiverUuid,jdbcType=VARCHAR}");
        }
        
        if (record.getReceiverName() != null) {
            sql.VALUES("receiver_name", "#{receiverName,jdbcType=VARCHAR}");
        }
        
        if (record.getAppealDate() != null) {
            sql.VALUES("appeal_date", "#{appealDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getFaceTalkDate() != null) {
            sql.VALUES("face_talk_date", "#{faceTalkDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getHandleBy() != null) {
            sql.VALUES("handle_by", "#{handleBy,jdbcType=VARCHAR}");
        }
        
        if (record.getRemark() != null) {
            sql.VALUES("remark", "#{remark,jdbcType=VARCHAR}");
        }
        
        if (record.getAppealDetail() != null) {
            sql.VALUES("appeal_detail", "#{appealDetail,jdbcType=VARCHAR}");
        }
        
        if (record.getExamine() != null) {
            sql.VALUES("examine", "#{examine,jdbcType=VARCHAR}");
        }
        
        if (record.getSolution() != null) {
            sql.VALUES("solution", "#{solution,jdbcType=VARCHAR}");
        }
        
        if (record.getCoordResults() != null) {
            sql.VALUES("coord_results", "#{coordResults,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateUser() != null) {
            sql.VALUES("create_user", "#{createUser,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateUser() != null) {
            sql.VALUES("update_user", "#{updateUser,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.VALUES("update_time", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getDeleted() != null) {
            sql.VALUES("deleted", "#{deleted,jdbcType=BIT}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_assess_appeal
     *
     * @mbg.generated Thu Apr 20 15:24:08 CST 2023
     */
    public String selectByExample(AppAssessAppealExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("uuid");
        } else {
            sql.SELECT("uuid");
        }
        sql.SELECT("user_uuid");
        sql.SELECT("user_name");
        sql.SELECT("dept_uuid");
        sql.SELECT("dept_name");
        sql.SELECT("role_uuid");
        sql.SELECT("role_name");
        sql.SELECT("appeal_text");
        sql.SELECT("receiver_uuid");
        sql.SELECT("receiver_name");
        sql.SELECT("appeal_date");
        sql.SELECT("face_talk_date");
        sql.SELECT("handle_by");
        sql.SELECT("remark");
        sql.SELECT("appeal_detail");
        sql.SELECT("examine");
        sql.SELECT("solution");
        sql.SELECT("coord_results");
        sql.SELECT("create_user");
        sql.SELECT("create_time");
        sql.SELECT("update_user");
        sql.SELECT("update_time");
        sql.SELECT("deleted");
        sql.FROM("app_assess_appeal");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_assess_appeal
     *
     * @mbg.generated Thu Apr 20 15:24:08 CST 2023
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        AppAssessAppeal record = (AppAssessAppeal) parameter.get("record");
        AppAssessAppealExample example = (AppAssessAppealExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("app_assess_appeal");
        
        if (record.getUuid() != null) {
            sql.SET("uuid = #{record.uuid,jdbcType=VARCHAR}");
        }
        
        if (record.getUserUuid() != null) {
            sql.SET("user_uuid = #{record.userUuid,jdbcType=VARCHAR}");
        }
        
        if (record.getUserName() != null) {
            sql.SET("user_name = #{record.userName,jdbcType=VARCHAR}");
        }
        
        if (record.getDeptUuid() != null) {
            sql.SET("dept_uuid = #{record.deptUuid,jdbcType=VARCHAR}");
        }
        
        if (record.getDeptName() != null) {
            sql.SET("dept_name = #{record.deptName,jdbcType=VARCHAR}");
        }
        
        if (record.getRoleUuid() != null) {
            sql.SET("role_uuid = #{record.roleUuid,jdbcType=VARCHAR}");
        }
        
        if (record.getRoleName() != null) {
            sql.SET("role_name = #{record.roleName,jdbcType=VARCHAR}");
        }
        
        if (record.getAppealText() != null) {
            sql.SET("appeal_text = #{record.appealText,jdbcType=VARCHAR}");
        }
        
        if (record.getReceiverUuid() != null) {
            sql.SET("receiver_uuid = #{record.receiverUuid,jdbcType=VARCHAR}");
        }
        
        if (record.getReceiverName() != null) {
            sql.SET("receiver_name = #{record.receiverName,jdbcType=VARCHAR}");
        }
        
        if (record.getAppealDate() != null) {
            sql.SET("appeal_date = #{record.appealDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getFaceTalkDate() != null) {
            sql.SET("face_talk_date = #{record.faceTalkDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getHandleBy() != null) {
            sql.SET("handle_by = #{record.handleBy,jdbcType=VARCHAR}");
        }
        
        if (record.getRemark() != null) {
            sql.SET("remark = #{record.remark,jdbcType=VARCHAR}");
        }
        
        if (record.getAppealDetail() != null) {
            sql.SET("appeal_detail = #{record.appealDetail,jdbcType=VARCHAR}");
        }
        
        if (record.getExamine() != null) {
            sql.SET("examine = #{record.examine,jdbcType=VARCHAR}");
        }
        
        if (record.getSolution() != null) {
            sql.SET("solution = #{record.solution,jdbcType=VARCHAR}");
        }
        
        if (record.getCoordResults() != null) {
            sql.SET("coord_results = #{record.coordResults,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateUser() != null) {
            sql.SET("create_user = #{record.createUser,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateUser() != null) {
            sql.SET("update_user = #{record.updateUser,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getDeleted() != null) {
            sql.SET("deleted = #{record.deleted,jdbcType=BIT}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_assess_appeal
     *
     * @mbg.generated Thu Apr 20 15:24:08 CST 2023
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("app_assess_appeal");
        
        sql.SET("uuid = #{record.uuid,jdbcType=VARCHAR}");
        sql.SET("user_uuid = #{record.userUuid,jdbcType=VARCHAR}");
        sql.SET("user_name = #{record.userName,jdbcType=VARCHAR}");
        sql.SET("dept_uuid = #{record.deptUuid,jdbcType=VARCHAR}");
        sql.SET("dept_name = #{record.deptName,jdbcType=VARCHAR}");
        sql.SET("role_uuid = #{record.roleUuid,jdbcType=VARCHAR}");
        sql.SET("role_name = #{record.roleName,jdbcType=VARCHAR}");
        sql.SET("appeal_text = #{record.appealText,jdbcType=VARCHAR}");
        sql.SET("receiver_uuid = #{record.receiverUuid,jdbcType=VARCHAR}");
        sql.SET("receiver_name = #{record.receiverName,jdbcType=VARCHAR}");
        sql.SET("appeal_date = #{record.appealDate,jdbcType=TIMESTAMP}");
        sql.SET("face_talk_date = #{record.faceTalkDate,jdbcType=TIMESTAMP}");
        sql.SET("handle_by = #{record.handleBy,jdbcType=VARCHAR}");
        sql.SET("remark = #{record.remark,jdbcType=VARCHAR}");
        sql.SET("appeal_detail = #{record.appealDetail,jdbcType=VARCHAR}");
        sql.SET("examine = #{record.examine,jdbcType=VARCHAR}");
        sql.SET("solution = #{record.solution,jdbcType=VARCHAR}");
        sql.SET("coord_results = #{record.coordResults,jdbcType=VARCHAR}");
        sql.SET("create_user = #{record.createUser,jdbcType=VARCHAR}");
        sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        sql.SET("update_user = #{record.updateUser,jdbcType=VARCHAR}");
        sql.SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        sql.SET("deleted = #{record.deleted,jdbcType=BIT}");
        
        AppAssessAppealExample example = (AppAssessAppealExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_assess_appeal
     *
     * @mbg.generated Thu Apr 20 15:24:08 CST 2023
     */
    protected void applyWhere(SQL sql, AppAssessAppealExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<AppAssessAppealExample.Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            AppAssessAppealExample.Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<AppAssessAppealExample.Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    AppAssessAppealExample.Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}