package com.zacboot.admin.work.mapper.provider;

import java.util.List;
import java.util.Map;

import com.zacboot.admin.work.beans.example.AppUserAssessExample;
import com.zacboot.system.core.entity.assess.AppUserAssess;
import org.apache.ibatis.jdbc.SQL;

public class AppUserAssessSqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_assess
     *
     * @mbg.generated Sun Apr 23 09:34:09 CST 2023
     */
    public String countByExample(AppUserAssessExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("app_user_assess");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_assess
     *
     * @mbg.generated Sun Apr 23 09:34:09 CST 2023
     */
    public String deleteByExample(AppUserAssessExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("app_user_assess");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_assess
     *
     * @mbg.generated Sun Apr 23 09:34:09 CST 2023
     */
    public String insertSelective(AppUserAssess record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("app_user_assess");
        
        if (record.getUuid() != null) {
            sql.VALUES("uuid", "#{uuid,jdbcType=VARCHAR}");
        }
        
        if (record.getUserUuid() != null) {
            sql.VALUES("user_uuid", "#{userUuid,jdbcType=VARCHAR}");
        }
        
        if (record.getUserName() != null) {
            sql.VALUES("user_name", "#{userName,jdbcType=VARCHAR}");
        }
        
        if (record.getTotalScore() != null) {
            sql.VALUES("total_score", "#{totalScore,jdbcType=VARCHAR}");
        }
        
        if (record.getAssessLevel() != null) {
            sql.VALUES("assess_level", "#{assessLevel,jdbcType=VARCHAR}");
        }
        
        if (record.getWorkListResponsibility() != null) {
            sql.VALUES("work_list_responsibility", "#{workListResponsibility,jdbcType=VARCHAR}");
        }
        
        if (record.getWorkListFlow() != null) {
            sql.VALUES("work_list_flow", "#{workListFlow,jdbcType=VARCHAR}");
        }
        
        if (record.getWorkListInventory() != null) {
            sql.VALUES("work_list_inventory", "#{workListInventory,jdbcType=VARCHAR}");
        }
        
        if (record.getWorkListFiles() != null) {
            sql.VALUES("work_list_files", "#{workListFiles,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateUser() != null) {
            sql.VALUES("create_user", "#{createUser,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateUser() != null) {
            sql.VALUES("update_user", "#{updateUser,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.VALUES("update_time", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getDeleted() != null) {
            sql.VALUES("deleted", "#{deleted,jdbcType=BIT}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_assess
     *
     * @mbg.generated Sun Apr 23 09:34:09 CST 2023
     */
    public String selectByExample(AppUserAssessExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("uuid");
        } else {
            sql.SELECT("uuid");
        }
        sql.SELECT("user_uuid");
        sql.SELECT("user_name");
        sql.SELECT("total_score");
        sql.SELECT("assess_level");
        sql.SELECT("work_list_responsibility");
        sql.SELECT("work_list_flow");
        sql.SELECT("work_list_inventory");
        sql.SELECT("work_list_files");
        sql.SELECT("create_user");
        sql.SELECT("create_time");
        sql.SELECT("update_user");
        sql.SELECT("update_time");
        sql.SELECT("deleted");
        sql.FROM("app_user_assess");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_assess
     *
     * @mbg.generated Sun Apr 23 09:34:09 CST 2023
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        AppUserAssess record = (AppUserAssess) parameter.get("record");
        AppUserAssessExample example = (AppUserAssessExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("app_user_assess");
        
        if (record.getUuid() != null) {
            sql.SET("uuid = #{record.uuid,jdbcType=VARCHAR}");
        }
        
        if (record.getUserUuid() != null) {
            sql.SET("user_uuid = #{record.userUuid,jdbcType=VARCHAR}");
        }
        
        if (record.getUserName() != null) {
            sql.SET("user_name = #{record.userName,jdbcType=VARCHAR}");
        }
        
        if (record.getTotalScore() != null) {
            sql.SET("total_score = #{record.totalScore,jdbcType=VARCHAR}");
        }
        
        if (record.getAssessLevel() != null) {
            sql.SET("assess_level = #{record.assessLevel,jdbcType=VARCHAR}");
        }
        
        if (record.getWorkListResponsibility() != null) {
            sql.SET("work_list_responsibility = #{record.workListResponsibility,jdbcType=VARCHAR}");
        }
        
        if (record.getWorkListFlow() != null) {
            sql.SET("work_list_flow = #{record.workListFlow,jdbcType=VARCHAR}");
        }
        
        if (record.getWorkListInventory() != null) {
            sql.SET("work_list_inventory = #{record.workListInventory,jdbcType=VARCHAR}");
        }
        
        if (record.getWorkListFiles() != null) {
            sql.SET("work_list_files = #{record.workListFiles,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateUser() != null) {
            sql.SET("create_user = #{record.createUser,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateUser() != null) {
            sql.SET("update_user = #{record.updateUser,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getDeleted() != null) {
            sql.SET("deleted = #{record.deleted,jdbcType=BIT}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_assess
     *
     * @mbg.generated Sun Apr 23 09:34:09 CST 2023
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("app_user_assess");
        
        sql.SET("uuid = #{record.uuid,jdbcType=VARCHAR}");
        sql.SET("user_uuid = #{record.userUuid,jdbcType=VARCHAR}");
        sql.SET("user_name = #{record.userName,jdbcType=VARCHAR}");
        sql.SET("total_score = #{record.totalScore,jdbcType=VARCHAR}");
        sql.SET("assess_level = #{record.assessLevel,jdbcType=VARCHAR}");
        sql.SET("work_list_responsibility = #{record.workListResponsibility,jdbcType=VARCHAR}");
        sql.SET("work_list_flow = #{record.workListFlow,jdbcType=VARCHAR}");
        sql.SET("work_list_inventory = #{record.workListInventory,jdbcType=VARCHAR}");
        sql.SET("work_list_files = #{record.workListFiles,jdbcType=VARCHAR}");
        sql.SET("create_user = #{record.createUser,jdbcType=VARCHAR}");
        sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        sql.SET("update_user = #{record.updateUser,jdbcType=VARCHAR}");
        sql.SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        sql.SET("deleted = #{record.deleted,jdbcType=BIT}");
        
        AppUserAssessExample example = (AppUserAssessExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_assess
     *
     * @mbg.generated Sun Apr 23 09:34:09 CST 2023
     */
    protected void applyWhere(SQL sql, AppUserAssessExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<AppUserAssessExample.Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            AppUserAssessExample.Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<AppUserAssessExample.Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    AppUserAssessExample.Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}