package com.zacboot.admin.work.mapper.provider;

import com.zacboot.admin.work.beans.example.AppUserMonthAssessExample;
import com.zacboot.system.core.entity.assess.AppUserMonthAssess;
import org.apache.ibatis.jdbc.SQL;

import java.util.List;
import java.util.Map;

public class AppUserMonthAssessSqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_month_assess
     *
     * @mbg.generated Sun Apr 23 09:34:40 CST 2023
     */
    public String countByExample(AppUserMonthAssessExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("app_user_month_assess");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_month_assess
     *
     * @mbg.generated Sun Apr 23 09:34:40 CST 2023
     */
    public String deleteByExample(AppUserMonthAssessExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("app_user_month_assess");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_month_assess
     *
     * @mbg.generated Sun Apr 23 09:34:40 CST 2023
     */
    public String insertSelective(AppUserMonthAssess record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("app_user_month_assess");
        
        if (record.getUuid() != null) {
            sql.VALUES("uuid", "#{uuid,jdbcType=VARCHAR}");
        }
        
        if (record.getUserUuid() != null) {
            sql.VALUES("user_uuid", "#{userUuid,jdbcType=VARCHAR}");
        }
        
        if (record.getCheckItem() != null) {
            sql.VALUES("check_item", "#{checkItem,jdbcType=VARCHAR}");
        }
        
        if (record.getTargetRequire() != null) {
            sql.VALUES("target_require", "#{targetRequire,jdbcType=VARCHAR}");
        }
        
        if (record.getTargetLevel() != null) {
            sql.VALUES("target_level", "#{targetLevel,jdbcType=VARCHAR}");
        }
        
        if (record.getCalFormula() != null) {
            sql.VALUES("cal_formula", "#{calFormula,jdbcType=VARCHAR}");
        }
        
        if (record.getNode() != null) {
            sql.VALUES("node", "#{node,jdbcType=VARCHAR}");
        }
        
        if (record.getWeightPer() != null) {
            sql.VALUES("weight_per", "#{weightPer,jdbcType=VARCHAR}");
        }
        
        if (record.getScore() != null) {
            sql.VALUES("score", "#{score,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateUser() != null) {
            sql.VALUES("create_user", "#{createUser,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateUser() != null) {
            sql.VALUES("update_user", "#{updateUser,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.VALUES("update_time", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getDeleted() != null) {
            sql.VALUES("deleted", "#{deleted,jdbcType=BIT}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_month_assess
     *
     * @mbg.generated Sun Apr 23 09:34:40 CST 2023
     */
    public String selectByExample(AppUserMonthAssessExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("uuid");
        } else {
            sql.SELECT("uuid");
        }
        sql.SELECT("user_uuid");
        sql.SELECT("check_item");
        sql.SELECT("target_require");
        sql.SELECT("target_level");
        sql.SELECT("cal_formula");
        sql.SELECT("node");
        sql.SELECT("weight_per");
        sql.SELECT("score");
        sql.SELECT("create_user");
        sql.SELECT("create_time");
        sql.SELECT("update_user");
        sql.SELECT("update_time");
        sql.SELECT("deleted");
        sql.FROM("app_user_month_assess");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_month_assess
     *
     * @mbg.generated Sun Apr 23 09:34:40 CST 2023
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        AppUserMonthAssess record = (AppUserMonthAssess) parameter.get("record");
        AppUserMonthAssessExample example = (AppUserMonthAssessExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("app_user_month_assess");
        
        if (record.getUuid() != null) {
            sql.SET("uuid = #{record.uuid,jdbcType=VARCHAR}");
        }
        
        if (record.getUserUuid() != null) {
            sql.SET("user_uuid = #{record.userUuid,jdbcType=VARCHAR}");
        }
        
        if (record.getCheckItem() != null) {
            sql.SET("check_item = #{record.checkItem,jdbcType=VARCHAR}");
        }
        
        if (record.getTargetRequire() != null) {
            sql.SET("target_require = #{record.targetRequire,jdbcType=VARCHAR}");
        }
        
        if (record.getTargetLevel() != null) {
            sql.SET("target_level = #{record.targetLevel,jdbcType=VARCHAR}");
        }
        
        if (record.getCalFormula() != null) {
            sql.SET("cal_formula = #{record.calFormula,jdbcType=VARCHAR}");
        }
        
        if (record.getNode() != null) {
            sql.SET("node = #{record.node,jdbcType=VARCHAR}");
        }
        
        if (record.getWeightPer() != null) {
            sql.SET("weight_per = #{record.weightPer,jdbcType=VARCHAR}");
        }
        
        if (record.getScore() != null) {
            sql.SET("score = #{record.score,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateUser() != null) {
            sql.SET("create_user = #{record.createUser,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateUser() != null) {
            sql.SET("update_user = #{record.updateUser,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getDeleted() != null) {
            sql.SET("deleted = #{record.deleted,jdbcType=BIT}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_month_assess
     *
     * @mbg.generated Sun Apr 23 09:34:40 CST 2023
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("app_user_month_assess");
        
        sql.SET("uuid = #{record.uuid,jdbcType=VARCHAR}");
        sql.SET("user_uuid = #{record.userUuid,jdbcType=VARCHAR}");
        sql.SET("check_item = #{record.checkItem,jdbcType=VARCHAR}");
        sql.SET("target_require = #{record.targetRequire,jdbcType=VARCHAR}");
        sql.SET("target_level = #{record.targetLevel,jdbcType=VARCHAR}");
        sql.SET("cal_formula = #{record.calFormula,jdbcType=VARCHAR}");
        sql.SET("node = #{record.node,jdbcType=VARCHAR}");
        sql.SET("weight_per = #{record.weightPer,jdbcType=VARCHAR}");
        sql.SET("score = #{record.score,jdbcType=VARCHAR}");
        sql.SET("create_user = #{record.createUser,jdbcType=VARCHAR}");
        sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        sql.SET("update_user = #{record.updateUser,jdbcType=VARCHAR}");
        sql.SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        sql.SET("deleted = #{record.deleted,jdbcType=BIT}");
        
        AppUserMonthAssessExample example = (AppUserMonthAssessExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_month_assess
     *
     * @mbg.generated Sun Apr 23 09:34:40 CST 2023
     */
    protected void applyWhere(SQL sql, AppUserMonthAssessExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<AppUserMonthAssessExample.Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            AppUserMonthAssessExample.Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<AppUserMonthAssessExample.Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    AppUserMonthAssessExample.Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}