spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.111.15.229:3306/htx?useUnicode=true&character_set_server=utf8mb4&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL&allowPublicKeyRetrieval=true
    username: root
    password: htx@LQJK
    hikari:
      #最小空闲链接数量
      minimum-idle: 5
      #空闲连接存活最大时间（默认600000）
      idle-timeout: 180000
      #最大连接数
      maximum-pool-size: 10
      #是否自动提交
      auto-commit: true
      #连接池中链接的最长生命周期默认30分钟 = 1800000
      max-lifetime: 1800000
      #链接超时时间
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    database: 0
    port: 6379
    host: htxalitest.lcago.cn
    password:
    key:
      admin: 'ums:admin'
      resourceList: 'ums:resourceList'
    expire:
      common: 86400 # 24小时
  cloud:
    nacos:
      discovery:
        server-addr: @nacos.config.server-addr@
      config:
        server-addr: @nacos.config.server-addr@
        file-extension: yaml
  config:
    import:
      - optional:nacos:htx-common.yml