package com.zacboot.admin.work.mapper;


import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.zacboot.admin.work.beans.example.AppAssessAppealExample;
import com.zacboot.admin.work.mapper.provider.AppAssessAppealSqlProvider;
import com.zacboot.system.core.entity.admin.AppAssessAppeal;
import org.apache.ibatis.annotations.*;

public interface AppAssessAppealMapper extends BaseMapper<AppAssessAppeal> {
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_three_report
     *
     * @mbg.generated Thu Apr 20 15:24:51 CST 2023
     */
    @SelectProvider(type= AppAssessAppealSqlProvider.class, method="countByExample")
    long countByExample(AppAssessAppealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_three_report
     *
     * @mbg.generated Thu Apr 20 15:24:51 CST 2023
     */
    @DeleteProvider(type=AppAssessAppealSqlProvider.class, method="deleteByExample")
    int deleteByExample(AppAssessAppealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_three_report
     *
     * @mbg.generated Thu Apr 20 15:24:51 CST 2023
     */
    @InsertProvider(type=AppAssessAppealSqlProvider.class, method="insertSelective")
    int insertSelective(AppAssessAppeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_three_report
     *
     * @mbg.generated Thu Apr 20 15:24:51 CST 2023
     */
    @UpdateProvider(type=AppAssessAppealSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") AppAssessAppeal record, @Param("example") AppAssessAppealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_three_report
     *
     * @mbg.generated Thu Apr 20 15:24:51 CST 2023
     */
    @UpdateProvider(type=AppAssessAppealSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") AppAssessAppeal record, @Param("example") AppAssessAppealExample example);
}