package com.zacboot.admin.work.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.zacboot.admin.work.beans.example.AppThreeReportExample;
import com.zacboot.admin.work.mapper.provider.AppThreeReportSqlProvider;
import com.zacboot.system.core.entity.admin.AppThreeReport;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface AppThreeReportMapper extends BaseMapper<AppThreeReport> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_three_report
     *
     * @mbg.generated Thu Apr 20 15:24:51 CST 2023
     */
    @SelectProvider(type= AppThreeReportSqlProvider.class, method="countByExample")
    long countByExample(AppThreeReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_three_report
     *
     * @mbg.generated Thu Apr 20 15:24:51 CST 2023
     */
    @DeleteProvider(type=AppThreeReportSqlProvider.class, method="deleteByExample")
    int deleteByExample(AppThreeReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_three_report
     *
     * @mbg.generated Thu Apr 20 15:24:51 CST 2023
     */
    @Insert({
        "insert into app_three_report (uuid, user_uuid, ",
        "user_name, dept_uuid, ",
        "dept_name, role_uuid, ",
        "role_name, report_type, ",
        "start_date, end_date, ",
        "complete, work_content, ",
        "unfinal_reason, difficulty, ",
        "todo_list, future_plans, ",
        "create_user, create_time, ",
        "update_user, update_time, ",
        "deleted)",
        "values (#{uuid,jdbcType=VARCHAR}, #{userUuid,jdbcType=VARCHAR}, ",
        "#{userName,jdbcType=VARCHAR}, #{deptUuid,jdbcType=VARCHAR}, ",
        "#{deptName,jdbcType=VARCHAR}, #{roleUuid,jdbcType=VARCHAR}, ",
        "#{roleName,jdbcType=VARCHAR}, #{reportType,jdbcType=VARCHAR}, ",
        "#{startDate,jdbcType=TIMESTAMP}, #{endDate,jdbcType=TIMESTAMP}, ",
        "#{complete,jdbcType=INTEGER}, #{workContent,jdbcType=VARCHAR}, ",
        "#{unfinalReason,jdbcType=VARCHAR}, #{difficulty,jdbcType=VARCHAR}, ",
        "#{todoList,jdbcType=VARCHAR}, #{futurePlans,jdbcType=VARCHAR}, ",
        "#{createUser,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateUser,jdbcType=VARCHAR}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{deleted,jdbcType=BIT})"
    })
    int insert(AppThreeReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_three_report
     *
     * @mbg.generated Thu Apr 20 15:24:51 CST 2023
     */
    @InsertProvider(type=AppThreeReportSqlProvider.class, method="insertSelective")
    int insertSelective(AppThreeReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_three_report
     *
     * @mbg.generated Thu Apr 20 15:24:51 CST 2023
     */
    @SelectProvider(type=AppThreeReportSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="uuid", property="uuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_uuid", property="userUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_name", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="dept_uuid", property="deptUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="dept_name", property="deptName", jdbcType=JdbcType.VARCHAR),
        @Result(column="role_uuid", property="roleUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="role_name", property="roleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="report_type", property="reportType", jdbcType=JdbcType.VARCHAR),
        @Result(column="start_date", property="startDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="end_date", property="endDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="complete", property="complete", jdbcType=JdbcType.INTEGER),
        @Result(column="work_content", property="workContent", jdbcType=JdbcType.VARCHAR),
        @Result(column="unfinal_reason", property="unfinalReason", jdbcType=JdbcType.VARCHAR),
        @Result(column="difficulty", property="difficulty", jdbcType=JdbcType.VARCHAR),
        @Result(column="todo_list", property="todoList", jdbcType=JdbcType.VARCHAR),
        @Result(column="future_plans", property="futurePlans", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_user", property="createUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_user", property="updateUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="deleted", property="deleted", jdbcType=JdbcType.BIT)
    })
    List<AppThreeReport> selectByExampleWithRowbounds(AppThreeReportExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_three_report
     *
     * @mbg.generated Thu Apr 20 15:24:51 CST 2023
     */
    @SelectProvider(type=AppThreeReportSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="uuid", property="uuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_uuid", property="userUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_name", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="dept_uuid", property="deptUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="dept_name", property="deptName", jdbcType=JdbcType.VARCHAR),
        @Result(column="role_uuid", property="roleUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="role_name", property="roleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="report_type", property="reportType", jdbcType=JdbcType.VARCHAR),
        @Result(column="start_date", property="startDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="end_date", property="endDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="complete", property="complete", jdbcType=JdbcType.INTEGER),
        @Result(column="work_content", property="workContent", jdbcType=JdbcType.VARCHAR),
        @Result(column="unfinal_reason", property="unfinalReason", jdbcType=JdbcType.VARCHAR),
        @Result(column="difficulty", property="difficulty", jdbcType=JdbcType.VARCHAR),
        @Result(column="todo_list", property="todoList", jdbcType=JdbcType.VARCHAR),
        @Result(column="future_plans", property="futurePlans", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_user", property="createUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_user", property="updateUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="deleted", property="deleted", jdbcType=JdbcType.BIT)
    })
    List<AppThreeReport> selectByExample(AppThreeReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_three_report
     *
     * @mbg.generated Thu Apr 20 15:24:51 CST 2023
     */
    @UpdateProvider(type=AppThreeReportSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") AppThreeReport record, @Param("example") AppThreeReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_three_report
     *
     * @mbg.generated Thu Apr 20 15:24:51 CST 2023
     */
    @UpdateProvider(type=AppThreeReportSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") AppThreeReport record, @Param("example") AppThreeReportExample example);
}