package com.zacboot.admin.work.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.zacboot.admin.work.beans.example.AppUserAssessExample;
import com.zacboot.admin.work.mapper.provider.AppUserAssessSqlProvider;
import java.util.List;
import com.zacboot.system.core.entity.assess.AppUserAssess;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface AppUserAssessMapper extends BaseMapper<AppUserAssess> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_assess
     *
     * @mbg.generated Sun Apr 23 09:34:09 CST 2023
     */
    @SelectProvider(type= AppUserAssessSqlProvider.class, method="countByExample")
    long countByExample(AppUserAssessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_assess
     *
     * @mbg.generated Sun Apr 23 09:34:09 CST 2023
     */
    @DeleteProvider(type=AppUserAssessSqlProvider.class, method="deleteByExample")
    int deleteByExample(AppUserAssessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_assess
     *
     * @mbg.generated Sun Apr 23 09:34:09 CST 2023
     */
    @Insert({
        "insert into app_user_assess (uuid, user_uuid, ",
        "user_name, total_score, ",
        "assess_level, work_list_responsibility, ",
        "work_list_flow, work_list_inventory, ",
        "work_list_files, create_user, ",
        "create_time, update_user, ",
        "update_time, deleted)",
        "values (#{uuid,jdbcType=VARCHAR}, #{userUuid,jdbcType=VARCHAR}, ",
        "#{userName,jdbcType=VARCHAR}, #{totalScore,jdbcType=VARCHAR}, ",
        "#{assessLevel,jdbcType=VARCHAR}, #{workListResponsibility,jdbcType=VARCHAR}, ",
        "#{workListFlow,jdbcType=VARCHAR}, #{workListInventory,jdbcType=VARCHAR}, ",
        "#{workListFiles,jdbcType=VARCHAR}, #{createUser,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateUser,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{deleted,jdbcType=BIT})"
    })
    int insert(AppUserAssess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_assess
     *
     * @mbg.generated Sun Apr 23 09:34:09 CST 2023
     */
    @InsertProvider(type=AppUserAssessSqlProvider.class, method="insertSelective")
    int insertSelective(AppUserAssess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_assess
     *
     * @mbg.generated Sun Apr 23 09:34:09 CST 2023
     */
    @SelectProvider(type=AppUserAssessSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="uuid", property="uuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_uuid", property="userUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_name", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="total_score", property="totalScore", jdbcType=JdbcType.VARCHAR),
        @Result(column="assess_level", property="assessLevel", jdbcType=JdbcType.VARCHAR),
        @Result(column="work_list_responsibility", property="workListResponsibility", jdbcType=JdbcType.VARCHAR),
        @Result(column="work_list_flow", property="workListFlow", jdbcType=JdbcType.VARCHAR),
        @Result(column="work_list_inventory", property="workListInventory", jdbcType=JdbcType.VARCHAR),
        @Result(column="work_list_files", property="workListFiles", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_user", property="createUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_user", property="updateUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="deleted", property="deleted", jdbcType=JdbcType.BIT)
    })
    List<AppUserAssess> selectByExampleWithRowbounds(AppUserAssessExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_assess
     *
     * @mbg.generated Sun Apr 23 09:34:09 CST 2023
     */
    @SelectProvider(type=AppUserAssessSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="uuid", property="uuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_uuid", property="userUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_name", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="total_score", property="totalScore", jdbcType=JdbcType.VARCHAR),
        @Result(column="assess_level", property="assessLevel", jdbcType=JdbcType.VARCHAR),
        @Result(column="work_list_responsibility", property="workListResponsibility", jdbcType=JdbcType.VARCHAR),
        @Result(column="work_list_flow", property="workListFlow", jdbcType=JdbcType.VARCHAR),
        @Result(column="work_list_inventory", property="workListInventory", jdbcType=JdbcType.VARCHAR),
        @Result(column="work_list_files", property="workListFiles", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_user", property="createUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_user", property="updateUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="deleted", property="deleted", jdbcType=JdbcType.BIT)
    })
    List<AppUserAssess> selectByExample(AppUserAssessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_assess
     *
     * @mbg.generated Sun Apr 23 09:34:09 CST 2023
     */
    @UpdateProvider(type=AppUserAssessSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") AppUserAssess record, @Param("example") AppUserAssessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_assess
     *
     * @mbg.generated Sun Apr 23 09:34:09 CST 2023
     */
    @UpdateProvider(type=AppUserAssessSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") AppUserAssess record, @Param("example") AppUserAssessExample example);
}