package com.zacboot.admin.work.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.zacboot.admin.work.beans.example.AppUserTimeAssessExample;
import com.zacboot.admin.work.mapper.provider.AppUserTimeAssessSqlProvider;
import com.zacboot.system.core.entity.assess.AppUserTimeAssess;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface AppUserTimeAssessMapper extends BaseMapper<AppUserTimeAssess> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_time_assess
     *
     * @mbg.generated Sun Apr 23 09:34:55 CST 2023
     */
    @SelectProvider(type= AppUserTimeAssessSqlProvider.class, method="countByExample")
    long countByExample(AppUserTimeAssessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_time_assess
     *
     * @mbg.generated Sun Apr 23 09:34:55 CST 2023
     */
    @DeleteProvider(type=AppUserTimeAssessSqlProvider.class, method="deleteByExample")
    int deleteByExample(AppUserTimeAssessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_time_assess
     *
     * @mbg.generated Sun Apr 23 09:34:55 CST 2023
     */
    @Insert({
        "insert into app_user_time_assess (uuid, user_uuid, ",
        "check_item, target_require, ",
        "`count`, count_unit, ",
        "detail_count, detail_unit, ",
        "create_user, create_time, ",
        "update_user, update_time, ",
        "deleted)",
        "values (#{uuid,jdbcType=VARCHAR}, #{userUuid,jdbcType=VARCHAR}, ",
        "#{checkItem,jdbcType=VARCHAR}, #{targetRequire,jdbcType=VARCHAR}, ",
        "#{count,jdbcType=INTEGER}, #{countUnit,jdbcType=VARCHAR}, ",
        "#{detailCount,jdbcType=INTEGER}, #{detailUnit,jdbcType=VARCHAR}, ",
        "#{createUser,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateUser,jdbcType=VARCHAR}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{deleted,jdbcType=BIT})"
    })
    int insert(AppUserTimeAssess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_time_assess
     *
     * @mbg.generated Sun Apr 23 09:34:55 CST 2023
     */
    @InsertProvider(type=AppUserTimeAssessSqlProvider.class, method="insertSelective")
    int insertSelective(AppUserTimeAssess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_time_assess
     *
     * @mbg.generated Sun Apr 23 09:34:55 CST 2023
     */
    @SelectProvider(type=AppUserTimeAssessSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="uuid", property="uuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_uuid", property="userUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="check_item", property="checkItem", jdbcType=JdbcType.VARCHAR),
        @Result(column="target_require", property="targetRequire", jdbcType=JdbcType.VARCHAR),
        @Result(column="count", property="count", jdbcType=JdbcType.INTEGER),
        @Result(column="count_unit", property="countUnit", jdbcType=JdbcType.VARCHAR),
        @Result(column="detail_count", property="detailCount", jdbcType=JdbcType.INTEGER),
        @Result(column="detail_unit", property="detailUnit", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_user", property="createUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_user", property="updateUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="deleted", property="deleted", jdbcType=JdbcType.BIT)
    })
    List<AppUserTimeAssess> selectByExampleWithRowbounds(AppUserTimeAssessExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_time_assess
     *
     * @mbg.generated Sun Apr 23 09:34:55 CST 2023
     */
    @SelectProvider(type=AppUserTimeAssessSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="uuid", property="uuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_uuid", property="userUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="check_item", property="checkItem", jdbcType=JdbcType.VARCHAR),
        @Result(column="target_require", property="targetRequire", jdbcType=JdbcType.VARCHAR),
        @Result(column="count", property="count", jdbcType=JdbcType.INTEGER),
        @Result(column="count_unit", property="countUnit", jdbcType=JdbcType.VARCHAR),
        @Result(column="detail_count", property="detailCount", jdbcType=JdbcType.INTEGER),
        @Result(column="detail_unit", property="detailUnit", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_user", property="createUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_user", property="updateUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="deleted", property="deleted", jdbcType=JdbcType.BIT)
    })
    List<AppUserTimeAssess> selectByExample(AppUserTimeAssessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_time_assess
     *
     * @mbg.generated Sun Apr 23 09:34:55 CST 2023
     */
    @UpdateProvider(type=AppUserTimeAssessSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") AppUserTimeAssess record, @Param("example") AppUserTimeAssessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_time_assess
     *
     * @mbg.generated Sun Apr 23 09:34:55 CST 2023
     */
    @UpdateProvider(type=AppUserTimeAssessSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") AppUserTimeAssess record, @Param("example") AppUserTimeAssessExample example);
}