package com.zacboot.admin.work.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.zacboot.admin.work.beans.example.AppUserMonthAssessExample;
import com.zacboot.admin.work.mapper.provider.AppUserMonthAssessSqlProvider;
import com.zacboot.system.core.entity.assess.AppUserMonthAssess;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface AppUserMonthAssessMapper extends BaseMapper<AppUserMonthAssess> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_month_assess
     *
     * @mbg.generated Sun Apr 23 09:34:40 CST 2023
     */
    @SelectProvider(type= AppUserMonthAssessSqlProvider.class, method="countByExample")
    long countByExample(AppUserMonthAssessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_month_assess
     *
     * @mbg.generated Sun Apr 23 09:34:40 CST 2023
     */
    @DeleteProvider(type=AppUserMonthAssessSqlProvider.class, method="deleteByExample")
    int deleteByExample(AppUserMonthAssessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_month_assess
     *
     * @mbg.generated Sun Apr 23 09:34:40 CST 2023
     */
    @Insert({
        "insert into app_user_month_assess (uuid, user_uuid, ",
        "check_item, target_require, ",
        "target_level, cal_formula, ",
        "node, weight_per, ",
        "score, create_user, ",
        "create_time, update_user, ",
        "update_time, deleted)",
        "values (#{uuid,jdbcType=VARCHAR}, #{userUuid,jdbcType=VARCHAR}, ",
        "#{checkItem,jdbcType=VARCHAR}, #{targetRequire,jdbcType=VARCHAR}, ",
        "#{targetLevel,jdbcType=VARCHAR}, #{calFormula,jdbcType=VARCHAR}, ",
        "#{node,jdbcType=VARCHAR}, #{weightPer,jdbcType=VARCHAR}, ",
        "#{score,jdbcType=VARCHAR}, #{createUser,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateUser,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{deleted,jdbcType=BIT})"
    })
    int insert(AppUserMonthAssess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_month_assess
     *
     * @mbg.generated Sun Apr 23 09:34:40 CST 2023
     */
    @InsertProvider(type=AppUserMonthAssessSqlProvider.class, method="insertSelective")
    int insertSelective(AppUserMonthAssess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_month_assess
     *
     * @mbg.generated Sun Apr 23 09:34:40 CST 2023
     */
    @SelectProvider(type=AppUserMonthAssessSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="uuid", property="uuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_uuid", property="userUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="check_item", property="checkItem", jdbcType=JdbcType.VARCHAR),
        @Result(column="target_require", property="targetRequire", jdbcType=JdbcType.VARCHAR),
        @Result(column="target_level", property="targetLevel", jdbcType=JdbcType.VARCHAR),
        @Result(column="cal_formula", property="calFormula", jdbcType=JdbcType.VARCHAR),
        @Result(column="node", property="node", jdbcType=JdbcType.VARCHAR),
        @Result(column="weight_per", property="weightPer", jdbcType=JdbcType.VARCHAR),
        @Result(column="score", property="score", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_user", property="createUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_user", property="updateUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="deleted", property="deleted", jdbcType=JdbcType.BIT)
    })
    List<AppUserMonthAssess> selectByExampleWithRowbounds(AppUserMonthAssessExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_month_assess
     *
     * @mbg.generated Sun Apr 23 09:34:40 CST 2023
     */
    @SelectProvider(type=AppUserMonthAssessSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="uuid", property="uuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_uuid", property="userUuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="check_item", property="checkItem", jdbcType=JdbcType.VARCHAR),
        @Result(column="target_require", property="targetRequire", jdbcType=JdbcType.VARCHAR),
        @Result(column="target_level", property="targetLevel", jdbcType=JdbcType.VARCHAR),
        @Result(column="cal_formula", property="calFormula", jdbcType=JdbcType.VARCHAR),
        @Result(column="node", property="node", jdbcType=JdbcType.VARCHAR),
        @Result(column="weight_per", property="weightPer", jdbcType=JdbcType.VARCHAR),
        @Result(column="score", property="score", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_user", property="createUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_user", property="updateUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="deleted", property="deleted", jdbcType=JdbcType.BIT)
    })
    List<AppUserMonthAssess> selectByExample(AppUserMonthAssessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_month_assess
     *
     * @mbg.generated Sun Apr 23 09:34:40 CST 2023
     */
    @UpdateProvider(type=AppUserMonthAssessSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") AppUserMonthAssess record, @Param("example") AppUserMonthAssessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zacboot..app_user_month_assess
     *
     * @mbg.generated Sun Apr 23 09:34:40 CST 2023
     */
    @UpdateProvider(type=AppUserMonthAssessSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") AppUserMonthAssess record, @Param("example") AppUserMonthAssessExample example);
}