package com.zac.flycloud.dao.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.zac.flycloud.bean.dto.SysRoleDTO;
import com.zac.flycloud.bean.dto.example.SysRoleDTOExample;
import com.zac.flycloud.dao.mapper.provider.SysRoleDTOSqlProvider;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface SysRoleDTOMapper extends BaseMapper<SysRoleDTO> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flycloud..sys_role
     *
     * @mbg.generated Fri Apr 30 23:19:11 CST 2021
     */
    @SelectProvider(type= SysRoleDTOSqlProvider.class, method="countByExample")
    long countByExample(SysRoleDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flycloud..sys_role
     *
     * @mbg.generated Fri Apr 30 23:19:11 CST 2021
     */
    @DeleteProvider(type=SysRoleDTOSqlProvider.class, method="deleteByExample")
    int deleteByExample(SysRoleDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flycloud..sys_role
     *
     * @mbg.generated Fri Apr 30 23:19:11 CST 2021
     */
    int insert(SysRoleDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flycloud..sys_role
     *
     * @mbg.generated Fri Apr 30 23:19:11 CST 2021
     */
    @InsertProvider(type=SysRoleDTOSqlProvider.class, method="insertSelective")
    int insertSelective(SysRoleDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flycloud..sys_role
     *
     * @mbg.generated Fri Apr 30 23:19:11 CST 2021
     */
    @SelectProvider(type=SysRoleDTOSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="uuid", property="uuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="role_name", property="roleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="role_code", property="roleCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_user", property="createUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_user", property="updateUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="deleted", property="deleted", jdbcType=JdbcType.BIT)
    })
    List<SysRoleDTO> selectByExampleWithRowbounds(SysRoleDTOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flycloud..sys_role
     *
     * @mbg.generated Fri Apr 30 23:19:11 CST 2021
     */
    @SelectProvider(type=SysRoleDTOSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="uuid", property="uuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="role_name", property="roleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="role_code", property="roleCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_user", property="createUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_user", property="updateUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="deleted", property="deleted", jdbcType=JdbcType.BIT)
    })
    List<SysRoleDTO> selectByExample(SysRoleDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flycloud..sys_role
     *
     * @mbg.generated Fri Apr 30 23:19:11 CST 2021
     */
    @UpdateProvider(type=SysRoleDTOSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SysRoleDTO record, @Param("example") SysRoleDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flycloud..sys_role
     *
     * @mbg.generated Fri Apr 30 23:19:11 CST 2021
     */
    @UpdateProvider(type=SysRoleDTOSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SysRoleDTO record, @Param("example") SysRoleDTOExample example);
}